package pub.qiuf.litemc.protocol.play.server;

import pub.qiuf.litemc.common.bean.datatype.Packet;
import com.google.common.io.ByteArrayDataInput;
import com.google.common.io.ByteStreams;
import pub.qiuf.litemc.common.util.ByteUtils;
import pub.qiuf.litemc.common.annotation.MCType;
import com.google.common.io.ByteArrayDataOutput;
import pub.qiuf.litemc.common.annotation.ServerPacket;
import lombok.Data;
import pub.qiuf.litemc.common.util.StreamUtils;

/**
 * Code is generated by <code>pub.qiuf.litemc.generator.ProtocolGenerator</code>, Please don't modify.<br>
 * See more detail from <a>https://wiki.vg/Protocol</a><br>
 */
@Data
public class Play_Server_ChatMessage extends Packet {
    /** Packet ID */
    @MCType("VarInt")
    private int packetId = 0x03;
    /** The client sends the raw input, not a Chat component */
    @MCType("String")
    private String message;

    @Override
    public byte[] encode() throws Exception {
        ByteArrayDataOutput packet = ByteStreams.newDataOutput();
        // Packet ID
        packet.write(ByteUtils.encodeVarInt(packetId));
        // The client sends the raw input, not a Chat component
        packet.write(ByteUtils.encodeString(message));
        return packet.toByteArray();
    }
    @Override
    public void decode(ByteArrayDataInput in) throws Exception {
        // Packet ID
        packetId = StreamUtils.readVarInt(in);
        // The client sends the raw input, not a Chat component
        message = StreamUtils.readString(in);
    }
    public static class Play_Server_ChatMessage_Builder {
        private Play_Server_ChatMessage object = new Play_Server_ChatMessage();
        /** Packet ID */
        public Play_Server_ChatMessage_Builder packetId(int packetId) {
            object.packetId = packetId;
            return this;
        }
        /** The client sends the raw input, not a Chat component */
        public Play_Server_ChatMessage_Builder message(String message) {
            object.message = message;
            return this;
        }
        public Play_Server_ChatMessage build() {
             return object;
        }

    }
    public static Play_Server_ChatMessage_Builder builder() {
        return new Play_Server_ChatMessage_Builder();
    }
}