package pub.qiuf.litemc.protocol.play.server;

import pub.qiuf.litemc.common.bean.datatype.Packet;
import com.google.common.io.ByteArrayDataInput;
import com.google.common.io.ByteStreams;
import pub.qiuf.litemc.common.util.ByteUtils;
import pub.qiuf.litemc.common.annotation.MCType;
import com.google.common.io.ByteArrayDataOutput;
import pub.qiuf.litemc.common.annotation.ServerPacket;
import lombok.Data;
import pub.qiuf.litemc.common.util.StreamUtils;

/**
 * Code is generated by <code>pub.qiuf.litemc.generator.ProtocolGenerator</code>, Please don't modify.<br>
 * See more detail from <a>https://wiki.vg/Protocol</a><br>
 */
@Data
public class Play_Server_SetBeaconEffect extends Packet {
    /** Packet ID */
    @MCType("VarInt")
    private int packetId = 0x22;
    /** A Potion ID. (Was a full Integer for the plugin message) */
    @MCType("VarInt")
    private int primaryEffect;
    /** A Potion ID. (Was a full Integer for the plugin message) */
    @MCType("VarInt")
    private int secondaryEffect;

    @Override
    public byte[] encode() throws Exception {
        ByteArrayDataOutput packet = ByteStreams.newDataOutput();
        // Packet ID
        packet.write(ByteUtils.encodeVarInt(packetId));
        // A Potion ID. (Was a full Integer for the plugin message)
        packet.write(ByteUtils.encodeVarInt(primaryEffect));
        // A Potion ID. (Was a full Integer for the plugin message)
        packet.write(ByteUtils.encodeVarInt(secondaryEffect));
        return packet.toByteArray();
    }
    @Override
    public void decode(ByteArrayDataInput in) throws Exception {
        // Packet ID
        packetId = StreamUtils.readVarInt(in);
        // A Potion ID. (Was a full Integer for the plugin message)
        primaryEffect = StreamUtils.readVarInt(in);
        // A Potion ID. (Was a full Integer for the plugin message)
        secondaryEffect = StreamUtils.readVarInt(in);
    }
    public static class Play_Server_SetBeaconEffect_Builder {
        private Play_Server_SetBeaconEffect object = new Play_Server_SetBeaconEffect();
        /** Packet ID */
        public Play_Server_SetBeaconEffect_Builder packetId(int packetId) {
            object.packetId = packetId;
            return this;
        }
        /** A Potion ID. (Was a full Integer for the plugin message) */
        public Play_Server_SetBeaconEffect_Builder primaryEffect(int primaryEffect) {
            object.primaryEffect = primaryEffect;
            return this;
        }
        /** A Potion ID. (Was a full Integer for the plugin message) */
        public Play_Server_SetBeaconEffect_Builder secondaryEffect(int secondaryEffect) {
            object.secondaryEffect = secondaryEffect;
            return this;
        }
        public Play_Server_SetBeaconEffect build() {
             return object;
        }

    }
    public static Play_Server_SetBeaconEffect_Builder builder() {
        return new Play_Server_SetBeaconEffect_Builder();
    }
}