package pub.qiuf.litemc.protocol.play.server;

import pub.qiuf.litemc.common.bean.datatype.Packet;
import com.google.common.io.ByteArrayDataInput;
import com.google.common.io.ByteStreams;
import pub.qiuf.litemc.common.util.ByteUtils;
import pub.qiuf.litemc.common.annotation.MCType;
import com.google.common.io.ByteArrayDataOutput;
import pub.qiuf.litemc.common.annotation.ServerPacket;
import lombok.Data;
import pub.qiuf.litemc.common.util.StreamUtils;

/**
 * Code is generated by <code>pub.qiuf.litemc.generator.ProtocolGenerator</code>, Please don't modify.<br>
 * See more detail from <a>https://wiki.vg/Protocol</a><br>
 */
@Data
public class Play_Server_ClientStatus extends Packet {
    /** Packet ID */
    @MCType("VarInt")
    private int packetId = 0x04;
    /** See below */
    @MCType("VarInt")
    private int actionId;

    @Override
    public byte[] encode() throws Exception {
        ByteArrayDataOutput packet = ByteStreams.newDataOutput();
        // Packet ID
        packet.write(ByteUtils.encodeVarInt(packetId));
        // See below
        packet.write(ByteUtils.encodeVarInt(actionId));
        return packet.toByteArray();
    }
    @Override
    public void decode(ByteArrayDataInput in) throws Exception {
        // Packet ID
        packetId = StreamUtils.readVarInt(in);
        // See below
        actionId = StreamUtils.readVarInt(in);
    }
    public static class Play_Server_ClientStatus_Builder {
        private Play_Server_ClientStatus object = new Play_Server_ClientStatus();
        /** Packet ID */
        public Play_Server_ClientStatus_Builder packetId(int packetId) {
            object.packetId = packetId;
            return this;
        }
        /** See below */
        public Play_Server_ClientStatus_Builder actionId(int actionId) {
            object.actionId = actionId;
            return this;
        }
        public Play_Server_ClientStatus build() {
             return object;
        }

    }
    public static Play_Server_ClientStatus_Builder builder() {
        return new Play_Server_ClientStatus_Builder();
    }
}