package pub.qiuf.litemc.protocol.play.server;

import pub.qiuf.litemc.common.bean.datatype.Packet;
import com.google.common.io.ByteArrayDataInput;
import com.google.common.io.ByteStreams;
import pub.qiuf.litemc.common.util.ByteUtils;
import pub.qiuf.litemc.common.annotation.MCType;
import com.google.common.io.ByteArrayDataOutput;
import pub.qiuf.litemc.common.annotation.ServerPacket;
import lombok.Data;
import pub.qiuf.litemc.common.util.StreamUtils;

/**
 * Code is generated by <code>pub.qiuf.litemc.generator.ProtocolGenerator</code>, Please don't modify.<br>
 * See more detail from <a>https://wiki.vg/Protocol</a><br>
 */
@Data
public class Play_Server_WindowConfirmation extends Packet {
    /** Packet ID */
    @MCType("VarInt")
    private int packetId = 0x07;
    /** The ID of the window that the action occurred in */
    @MCType("Byte")
    private byte windowId;
    /** Every action that is to be accepted has a unique number. This number is an incrementing integer (starting at 1) with separate counts for each window ID. */
    @MCType("Short")
    private short actionNumber;
    /** Whether the action was accepted */
    @MCType("Boolean")
    private boolean accepted;

    @Override
    public byte[] encode() throws Exception {
        ByteArrayDataOutput packet = ByteStreams.newDataOutput();
        // Packet ID
        packet.write(ByteUtils.encodeVarInt(packetId));
        // The ID of the window that the action occurred in
        packet.write(ByteUtils.encodeByte(windowId));
        // Every action that is to be accepted has a unique number. This number is an incrementing integer (starting at 1) with separate counts for each window ID.
        packet.write(ByteUtils.encodeShort(actionNumber));
        // Whether the action was accepted
        packet.write(ByteUtils.encodeBoolean(accepted));
        return packet.toByteArray();
    }
    @Override
    public void decode(ByteArrayDataInput in) throws Exception {
        // Packet ID
        packetId = StreamUtils.readVarInt(in);
        // The ID of the window that the action occurred in
        windowId = StreamUtils.readByte(in);
        // Every action that is to be accepted has a unique number. This number is an incrementing integer (starting at 1) with separate counts for each window ID.
        actionNumber = StreamUtils.readShort(in);
        // Whether the action was accepted
        accepted = StreamUtils.readBoolean(in);
    }
    public static class Play_Server_WindowConfirmation_Builder {
        private Play_Server_WindowConfirmation object = new Play_Server_WindowConfirmation();
        /** Packet ID */
        public Play_Server_WindowConfirmation_Builder packetId(int packetId) {
            object.packetId = packetId;
            return this;
        }
        /** The ID of the window that the action occurred in */
        public Play_Server_WindowConfirmation_Builder windowId(byte windowId) {
            object.windowId = windowId;
            return this;
        }
        /** Every action that is to be accepted has a unique number. This number is an incrementing integer (starting at 1) with separate counts for each window ID. */
        public Play_Server_WindowConfirmation_Builder actionNumber(short actionNumber) {
            object.actionNumber = actionNumber;
            return this;
        }
        /** Whether the action was accepted */
        public Play_Server_WindowConfirmation_Builder accepted(boolean accepted) {
            object.accepted = accepted;
            return this;
        }
        public Play_Server_WindowConfirmation build() {
             return object;
        }

    }
    public static Play_Server_WindowConfirmation_Builder builder() {
        return new Play_Server_WindowConfirmation_Builder();
    }
}