package pub.qiuf.litemc.protocol.play.server;

import pub.qiuf.litemc.common.bean.datatype.Packet;
import com.google.common.io.ByteArrayDataInput;
import com.google.common.io.ByteStreams;
import pub.qiuf.litemc.common.util.ByteUtils;
import pub.qiuf.litemc.common.annotation.MCType;
import com.google.common.io.ByteArrayDataOutput;
import pub.qiuf.litemc.common.annotation.ServerPacket;
import lombok.Data;
import pub.qiuf.litemc.common.util.StreamUtils;

/**
 * Code is generated by <code>pub.qiuf.litemc.generator.ProtocolGenerator</code>, Please don't modify.<br>
 * See more detail from <a>https://wiki.vg/Protocol</a><br>
 */
@Data
public class Play_Server_PlayerPosition extends Packet {
    /** Packet ID */
    @MCType("VarInt")
    private int packetId = 0x11;
    /** Absolute position */
    @MCType("Double")
    private double x;
    /** Absolute feet position, normally Head Y - 1.62 */
    @MCType("Double")
    private double feetY;
    /** Absolute position */
    @MCType("Double")
    private double z;
    /** True if the client is on the ground, false otherwise */
    @MCType("Boolean")
    private boolean onGround;

    @Override
    public byte[] encode() throws Exception {
        ByteArrayDataOutput packet = ByteStreams.newDataOutput();
        // Packet ID
        packet.write(ByteUtils.encodeVarInt(packetId));
        // Absolute position
        packet.write(ByteUtils.encodeDouble(x));
        // Absolute feet position, normally Head Y - 1.62
        packet.write(ByteUtils.encodeDouble(feetY));
        // Absolute position
        packet.write(ByteUtils.encodeDouble(z));
        // True if the client is on the ground, false otherwise
        packet.write(ByteUtils.encodeBoolean(onGround));
        return packet.toByteArray();
    }
    @Override
    public void decode(ByteArrayDataInput in) throws Exception {
        // Packet ID
        packetId = StreamUtils.readVarInt(in);
        // Absolute position
        x = StreamUtils.readDouble(in);
        // Absolute feet position, normally Head Y - 1.62
        feetY = StreamUtils.readDouble(in);
        // Absolute position
        z = StreamUtils.readDouble(in);
        // True if the client is on the ground, false otherwise
        onGround = StreamUtils.readBoolean(in);
    }
    public static class Play_Server_PlayerPosition_Builder {
        private Play_Server_PlayerPosition object = new Play_Server_PlayerPosition();
        /** Packet ID */
        public Play_Server_PlayerPosition_Builder packetId(int packetId) {
            object.packetId = packetId;
            return this;
        }
        /** Absolute position */
        public Play_Server_PlayerPosition_Builder x(double x) {
            object.x = x;
            return this;
        }
        /** Absolute feet position, normally Head Y - 1.62 */
        public Play_Server_PlayerPosition_Builder feetY(double feetY) {
            object.feetY = feetY;
            return this;
        }
        /** Absolute position */
        public Play_Server_PlayerPosition_Builder z(double z) {
            object.z = z;
            return this;
        }
        /** True if the client is on the ground, false otherwise */
        public Play_Server_PlayerPosition_Builder onGround(boolean onGround) {
            object.onGround = onGround;
            return this;
        }
        public Play_Server_PlayerPosition build() {
             return object;
        }

    }
    public static Play_Server_PlayerPosition_Builder builder() {
        return new Play_Server_PlayerPosition_Builder();
    }
}