package pub.qiuf.litemc.protocol.play.server;

import pub.qiuf.litemc.common.bean.datatype.Packet;
import com.google.common.io.ByteArrayDataInput;
import com.google.common.io.ByteStreams;
import pub.qiuf.litemc.common.util.ByteUtils;
import pub.qiuf.litemc.common.annotation.MCType;
import com.google.common.io.ByteArrayDataOutput;
import pub.qiuf.litemc.common.annotation.ServerPacket;
import lombok.Data;
import pub.qiuf.litemc.common.util.StreamUtils;

/**
 * Code is generated by <code>pub.qiuf.litemc.generator.ProtocolGenerator</code>, Please don't modify.<br>
 * See more detail from <a>https://wiki.vg/Protocol</a><br>
 */
@Data
public class Play_Server_AdvancementTab extends Packet {
    /** Packet ID */
    @MCType("VarInt")
    private int packetId = 0x20;
    /** 0: Opened tab, 1: Closed screen */
    @MCType("VarInt")
    private int action;
    /** Only present if action is Opened tab */
    @MCType("Identifier")
    private String tabId;

    @Override
    public byte[] encode() throws Exception {
        ByteArrayDataOutput packet = ByteStreams.newDataOutput();
        // Packet ID
        packet.write(ByteUtils.encodeVarInt(packetId));
        // 0: Opened tab, 1: Closed screen
        packet.write(ByteUtils.encodeVarInt(action));
        // Only present if action is Opened tab
        packet.write(ByteUtils.encodeIdentifier(tabId));
        return packet.toByteArray();
    }
    @Override
    public void decode(ByteArrayDataInput in) throws Exception {
        // Packet ID
        packetId = StreamUtils.readVarInt(in);
        // 0: Opened tab, 1: Closed screen
        action = StreamUtils.readVarInt(in);
        // Only present if action is Opened tab
        tabId = StreamUtils.readIdentifier(in);
    }
    public static class Play_Server_AdvancementTab_Builder {
        private Play_Server_AdvancementTab object = new Play_Server_AdvancementTab();
        /** Packet ID */
        public Play_Server_AdvancementTab_Builder packetId(int packetId) {
            object.packetId = packetId;
            return this;
        }
        /** 0: Opened tab, 1: Closed screen */
        public Play_Server_AdvancementTab_Builder action(int action) {
            object.action = action;
            return this;
        }
        /** Only present if action is Opened tab */
        public Play_Server_AdvancementTab_Builder tabId(String tabId) {
            object.tabId = tabId;
            return this;
        }
        public Play_Server_AdvancementTab build() {
             return object;
        }

    }
    public static Play_Server_AdvancementTab_Builder builder() {
        return new Play_Server_AdvancementTab_Builder();
    }
}