package pub.qiuf.litemc.protocol.play.server;

import pub.qiuf.litemc.common.bean.datatype.Packet;
import com.google.common.io.ByteArrayDataInput;
import com.google.common.io.ByteStreams;
import pub.qiuf.litemc.common.util.ByteUtils;
import pub.qiuf.litemc.common.annotation.MCType;
import com.google.common.io.ByteArrayDataOutput;
import pub.qiuf.litemc.common.annotation.ServerPacket;
import lombok.Data;
import pub.qiuf.litemc.common.util.StreamUtils;

/**
 * Code is generated by <code>pub.qiuf.litemc.generator.ProtocolGenerator</code>, Please don't modify.<br>
 * See more detail from <a>https://wiki.vg/Protocol</a><br>
 */
@Data
public class Play_Server_PlayerRotation extends Packet {
    /** Packet ID */
    @MCType("VarInt")
    private int packetId = 0x13;
    /** Absolute rotation on the X Axis, in degrees */
    @MCType("Float")
    private float yaw;
    /** Absolute rotation on the Y Axis, in degrees */
    @MCType("Float")
    private float pitch;
    /** True if the client is on the ground, False otherwise */
    @MCType("Boolean")
    private boolean onGround;

    @Override
    public byte[] encode() throws Exception {
        ByteArrayDataOutput packet = ByteStreams.newDataOutput();
        // Packet ID
        packet.write(ByteUtils.encodeVarInt(packetId));
        // Absolute rotation on the X Axis, in degrees
        packet.write(ByteUtils.encodeFloat(yaw));
        // Absolute rotation on the Y Axis, in degrees
        packet.write(ByteUtils.encodeFloat(pitch));
        // True if the client is on the ground, False otherwise
        packet.write(ByteUtils.encodeBoolean(onGround));
        return packet.toByteArray();
    }
    @Override
    public void decode(ByteArrayDataInput in) throws Exception {
        // Packet ID
        packetId = StreamUtils.readVarInt(in);
        // Absolute rotation on the X Axis, in degrees
        yaw = StreamUtils.readFloat(in);
        // Absolute rotation on the Y Axis, in degrees
        pitch = StreamUtils.readFloat(in);
        // True if the client is on the ground, False otherwise
        onGround = StreamUtils.readBoolean(in);
    }
    public static class Play_Server_PlayerRotation_Builder {
        private Play_Server_PlayerRotation object = new Play_Server_PlayerRotation();
        /** Packet ID */
        public Play_Server_PlayerRotation_Builder packetId(int packetId) {
            object.packetId = packetId;
            return this;
        }
        /** Absolute rotation on the X Axis, in degrees */
        public Play_Server_PlayerRotation_Builder yaw(float yaw) {
            object.yaw = yaw;
            return this;
        }
        /** Absolute rotation on the Y Axis, in degrees */
        public Play_Server_PlayerRotation_Builder pitch(float pitch) {
            object.pitch = pitch;
            return this;
        }
        /** True if the client is on the ground, False otherwise */
        public Play_Server_PlayerRotation_Builder onGround(boolean onGround) {
            object.onGround = onGround;
            return this;
        }
        public Play_Server_PlayerRotation build() {
             return object;
        }

    }
    public static Play_Server_PlayerRotation_Builder builder() {
        return new Play_Server_PlayerRotation_Builder();
    }
}