package pub.qiuf.litemc.protocol.play.server;

import pub.qiuf.litemc.common.bean.datatype.Packet;
import com.google.common.io.ByteArrayDataInput;
import com.google.common.io.ByteStreams;
import pub.qiuf.litemc.common.util.ByteUtils;
import pub.qiuf.litemc.common.annotation.MCType;
import com.google.common.io.ByteArrayDataOutput;
import pub.qiuf.litemc.common.annotation.ServerPacket;
import lombok.Data;
import pub.qiuf.litemc.common.util.StreamUtils;

/**
 * Code is generated by <code>pub.qiuf.litemc.generator.ProtocolGenerator</code>, Please don't modify.<br>
 * See more detail from <a>https://wiki.vg/Protocol</a><br>
 */
@Data
public class Play_Server_SteerBoat extends Packet {
    /** Packet ID */
    @MCType("VarInt")
    private int packetId = 0x16;
    @MCType("Boolean")
    private boolean leftPaddleTurning;
    @MCType("Boolean")
    private boolean rightPaddleTurning;

    @Override
    public byte[] encode() throws Exception {
        ByteArrayDataOutput packet = ByteStreams.newDataOutput();
        // Packet ID
        packet.write(ByteUtils.encodeVarInt(packetId));
        packet.write(ByteUtils.encodeBoolean(leftPaddleTurning));
        packet.write(ByteUtils.encodeBoolean(rightPaddleTurning));
        return packet.toByteArray();
    }
    @Override
    public void decode(ByteArrayDataInput in) throws Exception {
        // Packet ID
        packetId = StreamUtils.readVarInt(in);
        leftPaddleTurning = StreamUtils.readBoolean(in);
        rightPaddleTurning = StreamUtils.readBoolean(in);
    }
    public static class Play_Server_SteerBoat_Builder {
        private Play_Server_SteerBoat object = new Play_Server_SteerBoat();
        /** Packet ID */
        public Play_Server_SteerBoat_Builder packetId(int packetId) {
            object.packetId = packetId;
            return this;
        }
        public Play_Server_SteerBoat_Builder leftPaddleTurning(boolean leftPaddleTurning) {
            object.leftPaddleTurning = leftPaddleTurning;
            return this;
        }
        public Play_Server_SteerBoat_Builder rightPaddleTurning(boolean rightPaddleTurning) {
            object.rightPaddleTurning = rightPaddleTurning;
            return this;
        }
        public Play_Server_SteerBoat build() {
             return object;
        }

    }
    public static Play_Server_SteerBoat_Builder builder() {
        return new Play_Server_SteerBoat_Builder();
    }
}