package pub.qiuf.litemc.protocol.play.server;

import pub.qiuf.litemc.common.bean.datatype.Packet;
import com.google.common.io.ByteArrayDataInput;
import com.google.common.io.ByteStreams;
import pub.qiuf.litemc.common.util.ByteUtils;
import pub.qiuf.litemc.common.annotation.MCType;
import com.google.common.io.ByteArrayDataOutput;
import pub.qiuf.litemc.common.bean.datatype.Slot;
import pub.qiuf.litemc.common.annotation.ServerPacket;
import lombok.Data;
import pub.qiuf.litemc.common.util.StreamUtils;

/**
 * Code is generated by <code>pub.qiuf.litemc.generator.ProtocolGenerator</code>, Please don't modify.<br>
 * See more detail from <a>https://wiki.vg/Protocol</a><br>
 */
@Data
public class Play_Server_CreativeInventoryAction extends Packet {
    /** Packet ID */
    @MCType("VarInt")
    private int packetId = 0x26;
    /** Inventory slot */
    @MCType("Short")
    private short slot;
    @MCType("Slot")
    private Slot clickedItem;

    @Override
    public byte[] encode() throws Exception {
        ByteArrayDataOutput packet = ByteStreams.newDataOutput();
        // Packet ID
        packet.write(ByteUtils.encodeVarInt(packetId));
        // Inventory slot
        packet.write(ByteUtils.encodeShort(slot));
        packet.write(ByteUtils.encodeSlot(clickedItem));
        return packet.toByteArray();
    }
    @Override
    public void decode(ByteArrayDataInput in) throws Exception {
        // Packet ID
        packetId = StreamUtils.readVarInt(in);
        // Inventory slot
        slot = StreamUtils.readShort(in);
        clickedItem = StreamUtils.readSlot(in);
    }
    public static class Play_Server_CreativeInventoryAction_Builder {
        private Play_Server_CreativeInventoryAction object = new Play_Server_CreativeInventoryAction();
        /** Packet ID */
        public Play_Server_CreativeInventoryAction_Builder packetId(int packetId) {
            object.packetId = packetId;
            return this;
        }
        /** Inventory slot */
        public Play_Server_CreativeInventoryAction_Builder slot(short slot) {
            object.slot = slot;
            return this;
        }
        public Play_Server_CreativeInventoryAction_Builder clickedItem(Slot clickedItem) {
            object.clickedItem = clickedItem;
            return this;
        }
        public Play_Server_CreativeInventoryAction build() {
             return object;
        }

    }
    public static Play_Server_CreativeInventoryAction_Builder builder() {
        return new Play_Server_CreativeInventoryAction_Builder();
    }
}