package pub.qiuf.litemc.protocol.play.server;

import pub.qiuf.litemc.common.bean.datatype.Packet;
import com.google.common.io.ByteArrayDataInput;
import com.google.common.io.ByteStreams;
import pub.qiuf.litemc.common.util.ByteUtils;
import pub.qiuf.litemc.common.annotation.MCType;
import com.google.common.io.ByteArrayDataOutput;
import pub.qiuf.litemc.common.annotation.ServerPacket;
import lombok.Data;
import pub.qiuf.litemc.common.util.StreamUtils;

/**
 * Code is generated by <code>pub.qiuf.litemc.generator.ProtocolGenerator</code>, Please don't modify.<br>
 * See more detail from <a>https://wiki.vg/Protocol</a><br>
 */
@Data
public class Play_Server_Spectate extends Packet {
    /** Packet ID */
    @MCType("VarInt")
    private int packetId = 0x2B;
    /** UUID of the player to teleport to (can also be an entity UUID) */
    @MCType("UUID")
    private long[] targetPlayer = new long[2];

    @Override
    public byte[] encode() throws Exception {
        ByteArrayDataOutput packet = ByteStreams.newDataOutput();
        // Packet ID
        packet.write(ByteUtils.encodeVarInt(packetId));
        // UUID of the player to teleport to (can also be an entity UUID)
        for (long temp : targetPlayer) {
            packet.write(ByteUtils.encodeLong(temp));
        }
        return packet.toByteArray();
    }
    @Override
    public void decode(ByteArrayDataInput in) throws Exception {
        // Packet ID
        packetId = StreamUtils.readVarInt(in);
        // UUID of the player to teleport to (can also be an entity UUID)
        // TODO decode targetPlayer
    }
    public static class Play_Server_Spectate_Builder {
        private Play_Server_Spectate object = new Play_Server_Spectate();
        /** Packet ID */
        public Play_Server_Spectate_Builder packetId(int packetId) {
            object.packetId = packetId;
            return this;
        }
        /** UUID of the player to teleport to (can also be an entity UUID) */
        public Play_Server_Spectate_Builder targetPlayer(long[] targetPlayer) {
            object.targetPlayer = targetPlayer;
            return this;
        }
        public Play_Server_Spectate build() {
             return object;
        }

    }
    public static Play_Server_Spectate_Builder builder() {
        return new Play_Server_Spectate_Builder();
    }
}