package pub.qiuf.litemc.protocol.play.server;

import pub.qiuf.litemc.common.bean.datatype.Packet;
import com.google.common.io.ByteArrayDataInput;
import com.google.common.io.ByteStreams;
import pub.qiuf.litemc.common.util.ByteUtils;
import pub.qiuf.litemc.common.annotation.MCType;
import com.google.common.io.ByteArrayDataOutput;
import pub.qiuf.litemc.common.annotation.ServerPacket;
import lombok.Data;
import pub.qiuf.litemc.common.util.StreamUtils;

/**
 * Code is generated by <code>pub.qiuf.litemc.generator.ProtocolGenerator</code>, Please don't modify.<br>
 * See more detail from <a>https://wiki.vg/Protocol</a><br>
 */
@Data
public class Play_Server_SelectTrade extends Packet {
    /** Packet ID */
    @MCType("VarInt")
    private int packetId = 0x21;
    /** The selected slot int the players current (trading) inventory. (Was a full Integer for the plugin message) */
    @MCType("VarInt")
    private int selectedSlot;

    @Override
    public byte[] encode() throws Exception {
        ByteArrayDataOutput packet = ByteStreams.newDataOutput();
        // Packet ID
        packet.write(ByteUtils.encodeVarInt(packetId));
        // The selected slot int the players current (trading) inventory. (Was a full Integer for the plugin message)
        packet.write(ByteUtils.encodeVarInt(selectedSlot));
        return packet.toByteArray();
    }
    @Override
    public void decode(ByteArrayDataInput in) throws Exception {
        // Packet ID
        packetId = StreamUtils.readVarInt(in);
        // The selected slot int the players current (trading) inventory. (Was a full Integer for the plugin message)
        selectedSlot = StreamUtils.readVarInt(in);
    }
    public static class Play_Server_SelectTrade_Builder {
        private Play_Server_SelectTrade object = new Play_Server_SelectTrade();
        /** Packet ID */
        public Play_Server_SelectTrade_Builder packetId(int packetId) {
            object.packetId = packetId;
            return this;
        }
        /** The selected slot int the players current (trading) inventory. (Was a full Integer for the plugin message) */
        public Play_Server_SelectTrade_Builder selectedSlot(int selectedSlot) {
            object.selectedSlot = selectedSlot;
            return this;
        }
        public Play_Server_SelectTrade build() {
             return object;
        }

    }
    public static Play_Server_SelectTrade_Builder builder() {
        return new Play_Server_SelectTrade_Builder();
    }
}