package pub.qiuf.litemc.protocol.play.server;

import pub.qiuf.litemc.common.bean.datatype.Packet;
import com.google.common.io.ByteArrayDataInput;
import com.google.common.io.ByteStreams;
import pub.qiuf.litemc.common.util.ByteUtils;
import pub.qiuf.litemc.common.annotation.MCType;
import com.google.common.io.ByteArrayDataOutput;
import pub.qiuf.litemc.common.annotation.ServerPacket;
import lombok.Data;
import pub.qiuf.litemc.common.util.StreamUtils;

/**
 * Code is generated by <code>pub.qiuf.litemc.generator.ProtocolGenerator</code>, Please don't modify.<br>
 * See more detail from <a>https://wiki.vg/Protocol</a><br>
 */
@Data
public class Play_Server_ResourcePackStatus extends Packet {
    /** Packet ID */
    @MCType("VarInt")
    private int packetId = 0x1F;
    /** 0: successfully loaded, 1: declined, 2: failed download, 3: accepted */
    @MCType("VarInt")
    private int result;

    @Override
    public byte[] encode() throws Exception {
        ByteArrayDataOutput packet = ByteStreams.newDataOutput();
        // Packet ID
        packet.write(ByteUtils.encodeVarInt(packetId));
        // 0: successfully loaded, 1: declined, 2: failed download, 3: accepted
        packet.write(ByteUtils.encodeVarInt(result));
        return packet.toByteArray();
    }
    @Override
    public void decode(ByteArrayDataInput in) throws Exception {
        // Packet ID
        packetId = StreamUtils.readVarInt(in);
        // 0: successfully loaded, 1: declined, 2: failed download, 3: accepted
        result = StreamUtils.readVarInt(in);
    }
    public static class Play_Server_ResourcePackStatus_Builder {
        private Play_Server_ResourcePackStatus object = new Play_Server_ResourcePackStatus();
        /** Packet ID */
        public Play_Server_ResourcePackStatus_Builder packetId(int packetId) {
            object.packetId = packetId;
            return this;
        }
        /** 0: successfully loaded, 1: declined, 2: failed download, 3: accepted */
        public Play_Server_ResourcePackStatus_Builder result(int result) {
            object.result = result;
            return this;
        }
        public Play_Server_ResourcePackStatus build() {
             return object;
        }

    }
    public static Play_Server_ResourcePackStatus_Builder builder() {
        return new Play_Server_ResourcePackStatus_Builder();
    }
}