package pub.qiuf.litemc.protocol.play.server;

import pub.qiuf.litemc.common.bean.datatype.Packet;
import com.google.common.io.ByteArrayDataInput;
import com.google.common.io.ByteStreams;
import pub.qiuf.litemc.common.util.ByteUtils;
import pub.qiuf.litemc.common.annotation.MCType;
import com.google.common.io.ByteArrayDataOutput;
import pub.qiuf.litemc.common.annotation.ServerPacket;
import lombok.Data;
import pub.qiuf.litemc.common.util.StreamUtils;

/**
 * Code is generated by <code>pub.qiuf.litemc.generator.ProtocolGenerator</code>, Please don't modify.<br>
 * See more detail from <a>https://wiki.vg/Protocol</a><br>
 */
@Data
public class Play_Server_EntityNBTRequest extends Packet {
    /** Packet ID */
    @MCType("VarInt")
    private int packetId = 0x0D;
    /** An incremental ID so that the client can verify that the response matches. */
    @MCType("VarInt")
    private int transactionId;
    /** The ID of the entity to query. */
    @MCType("VarInt")
    private int entityId;

    @Override
    public byte[] encode() throws Exception {
        ByteArrayDataOutput packet = ByteStreams.newDataOutput();
        // Packet ID
        packet.write(ByteUtils.encodeVarInt(packetId));
        // An incremental ID so that the client can verify that the response matches.
        packet.write(ByteUtils.encodeVarInt(transactionId));
        // The ID of the entity to query.
        packet.write(ByteUtils.encodeVarInt(entityId));
        return packet.toByteArray();
    }
    @Override
    public void decode(ByteArrayDataInput in) throws Exception {
        // Packet ID
        packetId = StreamUtils.readVarInt(in);
        // An incremental ID so that the client can verify that the response matches.
        transactionId = StreamUtils.readVarInt(in);
        // The ID of the entity to query.
        entityId = StreamUtils.readVarInt(in);
    }
    public static class Play_Server_EntityNBTRequest_Builder {
        private Play_Server_EntityNBTRequest object = new Play_Server_EntityNBTRequest();
        /** Packet ID */
        public Play_Server_EntityNBTRequest_Builder packetId(int packetId) {
            object.packetId = packetId;
            return this;
        }
        /** An incremental ID so that the client can verify that the response matches. */
        public Play_Server_EntityNBTRequest_Builder transactionId(int transactionId) {
            object.transactionId = transactionId;
            return this;
        }
        /** The ID of the entity to query. */
        public Play_Server_EntityNBTRequest_Builder entityId(int entityId) {
            object.entityId = entityId;
            return this;
        }
        public Play_Server_EntityNBTRequest build() {
             return object;
        }

    }
    public static Play_Server_EntityNBTRequest_Builder builder() {
        return new Play_Server_EntityNBTRequest_Builder();
    }
}