package pub.qiuf.litemc.protocol.play.server;

import pub.qiuf.litemc.common.bean.datatype.Packet;
import com.google.common.io.ByteArrayDataInput;
import com.google.common.io.ByteStreams;
import pub.qiuf.litemc.common.util.ByteUtils;
import pub.qiuf.litemc.common.annotation.MCType;
import com.google.common.io.ByteArrayDataOutput;
import pub.qiuf.litemc.common.annotation.ServerPacket;
import lombok.Data;
import pub.qiuf.litemc.common.util.StreamUtils;

/**
 * Code is generated by <code>pub.qiuf.litemc.generator.ProtocolGenerator</code>, Please don't modify.<br>
 * See more detail from <a>https://wiki.vg/Protocol</a><br>
 */
@Data
public class Play_Server_Animation extends Packet {
    /** Packet ID */
    @MCType("VarInt")
    private int packetId = 0x2A;
    /** Hand used for the animation. 0: main hand, 1: off hand. */
    @MCType("VarInt")
    private int hand;

    @Override
    public byte[] encode() throws Exception {
        ByteArrayDataOutput packet = ByteStreams.newDataOutput();
        // Packet ID
        packet.write(ByteUtils.encodeVarInt(packetId));
        // Hand used for the animation. 0: main hand, 1: off hand.
        packet.write(ByteUtils.encodeVarInt(hand));
        return packet.toByteArray();
    }
    @Override
    public void decode(ByteArrayDataInput in) throws Exception {
        // Packet ID
        packetId = StreamUtils.readVarInt(in);
        // Hand used for the animation. 0: main hand, 1: off hand.
        hand = StreamUtils.readVarInt(in);
    }
    public static class Play_Server_Animation_Builder {
        private Play_Server_Animation object = new Play_Server_Animation();
        /** Packet ID */
        public Play_Server_Animation_Builder packetId(int packetId) {
            object.packetId = packetId;
            return this;
        }
        /** Hand used for the animation. 0: main hand, 1: off hand. */
        public Play_Server_Animation_Builder hand(int hand) {
            object.hand = hand;
            return this;
        }
        public Play_Server_Animation build() {
             return object;
        }

    }
    public static Play_Server_Animation_Builder builder() {
        return new Play_Server_Animation_Builder();
    }
}