package pub.qiuf.litemc.protocol.status.server;

import pub.qiuf.litemc.common.bean.datatype.Packet;
import com.google.common.io.ByteArrayDataInput;
import com.google.common.io.ByteStreams;
import pub.qiuf.litemc.common.util.ByteUtils;
import pub.qiuf.litemc.common.annotation.MCType;
import com.google.common.io.ByteArrayDataOutput;
import pub.qiuf.litemc.common.annotation.ServerPacket;
import lombok.Data;
import pub.qiuf.litemc.common.util.StreamUtils;

/**
 * Code is generated by <code>pub.qiuf.litemc.generator.ProtocolGenerator</code>, Please don't modify.<br>
 * See more detail from <a>https://wiki.vg/Protocol</a><br>
 */
@Data
public class Status_Server_Ping extends Packet {
    /** Packet ID */
    @MCType("VarInt")
    private int packetId = 0x01;
    /** May be any number. Notchian clients use a system-dependent time value which is counted in milliseconds. */
    @MCType("Long")
    private long payload;

    @Override
    public byte[] encode() throws Exception {
        ByteArrayDataOutput packet = ByteStreams.newDataOutput();
        // Packet ID
        packet.write(ByteUtils.encodeVarInt(packetId));
        // May be any number. Notchian clients use a system-dependent time value which is counted in milliseconds.
        packet.write(ByteUtils.encodeLong(payload));
        return packet.toByteArray();
    }
    @Override
    public void decode(ByteArrayDataInput in) throws Exception {
        // Packet ID
        packetId = StreamUtils.readVarInt(in);
        // May be any number. Notchian clients use a system-dependent time value which is counted in milliseconds.
        payload = StreamUtils.readLong(in);
    }
    public static class Status_Server_Ping_Builder {
        private Status_Server_Ping object = new Status_Server_Ping();
        /** Packet ID */
        public Status_Server_Ping_Builder packetId(int packetId) {
            object.packetId = packetId;
            return this;
        }
        /** May be any number. Notchian clients use a system-dependent time value which is counted in milliseconds. */
        public Status_Server_Ping_Builder payload(long payload) {
            object.payload = payload;
            return this;
        }
        public Status_Server_Ping build() {
             return object;
        }

    }
    public static Status_Server_Ping_Builder builder() {
        return new Status_Server_Ping_Builder();
    }
}