package pub.qiuf.litemc.protocol.handshaking.server;

import pub.qiuf.litemc.common.bean.datatype.Packet;
import com.google.common.io.ByteArrayDataInput;
import com.google.common.io.ByteStreams;
import pub.qiuf.litemc.common.util.ByteUtils;
import pub.qiuf.litemc.common.annotation.MCType;
import com.google.common.io.ByteArrayDataOutput;
import pub.qiuf.litemc.common.annotation.ServerPacket;
import lombok.Data;
import pub.qiuf.litemc.common.util.StreamUtils;

/**
 * Code is generated by <code>pub.qiuf.litemc.generator.ProtocolGenerator</code>, Please don't modify.<br>
 * See more detail from <a>https://wiki.vg/Protocol</a><br>
 */
@Data
public class Handshaking_Server_LegacyServerListPing extends Packet {
    /** Packet ID */
    @MCType("VarInt")
    private int packetId = 0xFE;
    /** always 1 (0x01) */
    @MCType("UnsignedByte")
    private int payload;

    @Override
    public byte[] encode() throws Exception {
        ByteArrayDataOutput packet = ByteStreams.newDataOutput();
        // Packet ID
        packet.write(ByteUtils.encodeVarInt(packetId));
        // always 1 (0x01)
        packet.write(ByteUtils.encodeUnsignedByte(payload));
        return packet.toByteArray();
    }
    @Override
    public void decode(ByteArrayDataInput in) throws Exception {
        // Packet ID
        packetId = StreamUtils.readVarInt(in);
        // always 1 (0x01)
        payload = StreamUtils.readUnsignedByte(in);
    }
    public static class Handshaking_Server_LegacyServerListPing_Builder {
        private Handshaking_Server_LegacyServerListPing object = new Handshaking_Server_LegacyServerListPing();
        /** Packet ID */
        public Handshaking_Server_LegacyServerListPing_Builder packetId(int packetId) {
            object.packetId = packetId;
            return this;
        }
        /** always 1 (0x01) */
        public Handshaking_Server_LegacyServerListPing_Builder payload(int payload) {
            object.payload = payload;
            return this;
        }
        public Handshaking_Server_LegacyServerListPing build() {
             return object;
        }

    }
    public static Handshaking_Server_LegacyServerListPing_Builder builder() {
        return new Handshaking_Server_LegacyServerListPing_Builder();
    }
}