package pub.qiuf.litemc.protocol.login.server;

import pub.qiuf.litemc.common.bean.datatype.Packet;
import com.google.common.io.ByteArrayDataInput;
import com.google.common.io.ByteStreams;
import pub.qiuf.litemc.common.util.ByteUtils;
import pub.qiuf.litemc.common.annotation.MCType;
import com.google.common.io.ByteArrayDataOutput;
import pub.qiuf.litemc.common.annotation.ServerPacket;
import lombok.Data;
import pub.qiuf.litemc.common.util.StreamUtils;

/**
 * Code is generated by <code>pub.qiuf.litemc.generator.ProtocolGenerator</code>, Please don't modify.<br>
 * See more detail from <a>https://wiki.vg/Protocol</a><br>
 */
@Data
public class Login_Server_LoginStart extends Packet {
    /** Packet ID */
    @MCType("VarInt")
    private int packetId = 0x00;
    /** Player's Username */
    @MCType("String")
    private String name;

    @Override
    public byte[] encode() throws Exception {
        ByteArrayDataOutput packet = ByteStreams.newDataOutput();
        // Packet ID
        packet.write(ByteUtils.encodeVarInt(packetId));
        // Player's Username
        packet.write(ByteUtils.encodeString(name));
        return packet.toByteArray();
    }
    @Override
    public void decode(ByteArrayDataInput in) throws Exception {
        // Packet ID
        packetId = StreamUtils.readVarInt(in);
        // Player's Username
        name = StreamUtils.readString(in);
    }
    public static class Login_Server_LoginStart_Builder {
        private Login_Server_LoginStart object = new Login_Server_LoginStart();
        /** Packet ID */
        public Login_Server_LoginStart_Builder packetId(int packetId) {
            object.packetId = packetId;
            return this;
        }
        /** Player's Username */
        public Login_Server_LoginStart_Builder name(String name) {
            object.name = name;
            return this;
        }
        public Login_Server_LoginStart build() {
             return object;
        }

    }
    public static Login_Server_LoginStart_Builder builder() {
        return new Login_Server_LoginStart_Builder();
    }
}