package pub.qiuf.litemc.protocol.status.client;

import pub.qiuf.litemc.common.bean.datatype.Packet;
import com.google.common.io.ByteArrayDataInput;
import com.google.common.io.ByteStreams;
import pub.qiuf.litemc.common.util.ByteUtils;
import pub.qiuf.litemc.common.annotation.MCType;
import com.google.common.io.ByteArrayDataOutput;
import pub.qiuf.litemc.common.annotation.ServerPacket;
import lombok.Data;
import pub.qiuf.litemc.common.util.StreamUtils;

/**
 * Code is generated by <code>pub.qiuf.litemc.generator.ProtocolGenerator</code>, Please don't modify.<br>
 * See more detail from <a>https://wiki.vg/Protocol</a><br>
 */
@Data
@ServerPacket(0x01)
public class Status_Client_Pong extends Packet {
    /** Packet ID */
    @MCType("VarInt")
    private int packetId = 0x01;
    /** Should be the same as sent by the client */
    @MCType("Long")
    private long payload;

    @Override
    public byte[] encode() throws Exception {
        ByteArrayDataOutput packet = ByteStreams.newDataOutput();
        // Packet ID
        packet.write(ByteUtils.encodeVarInt(packetId));
        // Should be the same as sent by the client
        packet.write(ByteUtils.encodeLong(payload));
        return packet.toByteArray();
    }
    @Override
    public void decode(ByteArrayDataInput in) throws Exception {
        // Packet ID
        packetId = StreamUtils.readVarInt(in);
        // Should be the same as sent by the client
        payload = StreamUtils.readLong(in);
    }
    public static class Status_Client_Pong_Builder {
        private Status_Client_Pong object = new Status_Client_Pong();
        /** Packet ID */
        public Status_Client_Pong_Builder packetId(int packetId) {
            object.packetId = packetId;
            return this;
        }
        /** Should be the same as sent by the client */
        public Status_Client_Pong_Builder payload(long payload) {
            object.payload = payload;
            return this;
        }
        public Status_Client_Pong build() {
             return object;
        }

    }
    public static Status_Client_Pong_Builder builder() {
        return new Status_Client_Pong_Builder();
    }
}