package pub.qiuf.litemc.protocol.status.client;

import pub.qiuf.litemc.common.bean.datatype.Packet;
import com.google.common.io.ByteArrayDataInput;
import com.google.common.io.ByteStreams;
import pub.qiuf.litemc.common.util.ByteUtils;
import pub.qiuf.litemc.common.annotation.MCType;
import com.google.common.io.ByteArrayDataOutput;
import pub.qiuf.litemc.common.annotation.ServerPacket;
import lombok.Data;
import pub.qiuf.litemc.common.util.StreamUtils;

/**
 * Code is generated by <code>pub.qiuf.litemc.generator.ProtocolGenerator</code>, Please don't modify.<br>
 * See more detail from <a>https://wiki.vg/Protocol</a><br>
 */
@Data
@ServerPacket(0x00)
public class Status_Client_Response extends Packet {
    /** Packet ID */
    @MCType("VarInt")
    private int packetId = 0x00;

    @Override
    public byte[] encode() throws Exception {
        ByteArrayDataOutput packet = ByteStreams.newDataOutput();
        // Packet ID
        packet.write(ByteUtils.encodeVarInt(packetId));
        return packet.toByteArray();
    }
    @Override
    public void decode(ByteArrayDataInput in) throws Exception {
        // Packet ID
        packetId = StreamUtils.readVarInt(in);
    }
    public static class Status_Client_Response_Builder {
        private Status_Client_Response object = new Status_Client_Response();
        /** Packet ID */
        public Status_Client_Response_Builder packetId(int packetId) {
            object.packetId = packetId;
            return this;
        }
        public Status_Client_Response build() {
             return object;
        }

    }
    public static Status_Client_Response_Builder builder() {
        return new Status_Client_Response_Builder();
    }
}