package pub.qiuf.litemc.protocol.login.client;

import pub.qiuf.litemc.common.bean.datatype.Packet;
import com.google.common.io.ByteArrayDataInput;
import com.google.common.io.ByteStreams;
import pub.qiuf.litemc.common.util.ByteUtils;
import pub.qiuf.litemc.common.annotation.MCType;
import com.google.common.io.ByteArrayDataOutput;
import pub.qiuf.litemc.common.annotation.ServerPacket;
import lombok.Data;
import pub.qiuf.litemc.common.util.StreamUtils;

/**
 * Code is generated by <code>pub.qiuf.litemc.generator.ProtocolGenerator</code>, Please don't modify.<br>
 * See more detail from <a>https://wiki.vg/Protocol</a><br>
 */
@Data
@ServerPacket(0x04)
public class Login_Client_LoginPluginRequest extends Packet {
    /** Packet ID */
    @MCType("VarInt")
    private int packetId = 0x04;
    /** Generated by the server - should be unique to the connection. */
    @MCType("VarInt")
    private int messageId;
    /** Name of the plugin channel used to send the data */
    @MCType("Identifier")
    private String channel;
    /** Any data, depending on the channel. The length of this array must be inferred from the packet length. */
    @MCType("Byte")
    private byte[] data;

    @Override
    public byte[] encode() throws Exception {
        ByteArrayDataOutput packet = ByteStreams.newDataOutput();
        // Packet ID
        packet.write(ByteUtils.encodeVarInt(packetId));
        // Generated by the server - should be unique to the connection.
        packet.write(ByteUtils.encodeVarInt(messageId));
        // Name of the plugin channel used to send the data
        packet.write(ByteUtils.encodeIdentifier(channel));
        // Any data, depending on the channel. The length of this array must be inferred from the packet length.
        packet.write(data);
        return packet.toByteArray();
    }
    @Override
    public void decode(ByteArrayDataInput in) throws Exception {
        // Packet ID
        packetId = StreamUtils.readVarInt(in);
        // Generated by the server - should be unique to the connection.
        messageId = StreamUtils.readVarInt(in);
        // Name of the plugin channel used to send the data
        channel = StreamUtils.readIdentifier(in);
        // Any data, depending on the channel. The length of this array must be inferred from the packet length.
        // TODO decode data
    }
    public static class Login_Client_LoginPluginRequest_Builder {
        private Login_Client_LoginPluginRequest object = new Login_Client_LoginPluginRequest();
        /** Packet ID */
        public Login_Client_LoginPluginRequest_Builder packetId(int packetId) {
            object.packetId = packetId;
            return this;
        }
        /** Generated by the server - should be unique to the connection. */
        public Login_Client_LoginPluginRequest_Builder messageId(int messageId) {
            object.messageId = messageId;
            return this;
        }
        /** Name of the plugin channel used to send the data */
        public Login_Client_LoginPluginRequest_Builder channel(String channel) {
            object.channel = channel;
            return this;
        }
        /** Any data, depending on the channel. The length of this array must be inferred from the packet length. */
        public Login_Client_LoginPluginRequest_Builder data(byte[] data) {
            object.data = data;
            return this;
        }
        public Login_Client_LoginPluginRequest build() {
             return object;
        }

    }
    public static Login_Client_LoginPluginRequest_Builder builder() {
        return new Login_Client_LoginPluginRequest_Builder();
    }
}