package pub.qiuf.litemc.protocol.login.client;

import pub.qiuf.litemc.common.bean.datatype.Packet;
import com.google.common.io.ByteArrayDataInput;
import com.google.common.io.ByteStreams;
import pub.qiuf.litemc.common.util.ByteUtils;
import pub.qiuf.litemc.common.annotation.MCType;
import com.google.common.io.ByteArrayDataOutput;
import pub.qiuf.litemc.common.annotation.ServerPacket;
import lombok.Data;
import pub.qiuf.litemc.common.util.StreamUtils;

/**
 * Code is generated by <code>pub.qiuf.litemc.generator.ProtocolGenerator</code>, Please don't modify.<br>
 * See more detail from <a>https://wiki.vg/Protocol</a><br>
 */
@Data
@ServerPacket(0x03)
public class Login_Client_SetCompression extends Packet {
    /** Packet ID */
    @MCType("VarInt")
    private int packetId = 0x03;
    /** Maximum size of a packet before it is compressed */
    @MCType("VarInt")
    private int threshold;

    @Override
    public byte[] encode() throws Exception {
        ByteArrayDataOutput packet = ByteStreams.newDataOutput();
        // Packet ID
        packet.write(ByteUtils.encodeVarInt(packetId));
        // Maximum size of a packet before it is compressed
        packet.write(ByteUtils.encodeVarInt(threshold));
        return packet.toByteArray();
    }
    @Override
    public void decode(ByteArrayDataInput in) throws Exception {
        // Packet ID
        packetId = StreamUtils.readVarInt(in);
        // Maximum size of a packet before it is compressed
        threshold = StreamUtils.readVarInt(in);
    }
    public static class Login_Client_SetCompression_Builder {
        private Login_Client_SetCompression object = new Login_Client_SetCompression();
        /** Packet ID */
        public Login_Client_SetCompression_Builder packetId(int packetId) {
            object.packetId = packetId;
            return this;
        }
        /** Maximum size of a packet before it is compressed */
        public Login_Client_SetCompression_Builder threshold(int threshold) {
            object.threshold = threshold;
            return this;
        }
        public Login_Client_SetCompression build() {
             return object;
        }

    }
    public static Login_Client_SetCompression_Builder builder() {
        return new Login_Client_SetCompression_Builder();
    }
}