package pub.qiuf.litemc.protocol.play.client;

import pub.qiuf.litemc.common.bean.datatype.Packet;
import com.google.common.io.ByteArrayDataInput;
import com.google.common.io.ByteStreams;
import pub.qiuf.litemc.common.util.ByteUtils;
import pub.qiuf.litemc.common.annotation.MCType;
import com.google.common.io.ByteArrayDataOutput;
import pub.qiuf.litemc.common.annotation.ServerPacket;
import lombok.Data;
import pub.qiuf.litemc.common.util.StreamUtils;

/**
 * Code is generated by <code>pub.qiuf.litemc.generator.ProtocolGenerator</code>, Please don't modify.<br>
 * See more detail from <a>https://wiki.vg/Protocol</a><br>
 */
@Data
@ServerPacket(0x01)
public class Play_Client_SpawnExperienceOrb extends Packet {
    /** Packet ID */
    @MCType("VarInt")
    private int packetId = 0x01;
    @MCType("VarInt")
    private int entityId;
    @MCType("Double")
    private double x;
    @MCType("Double")
    private double y;
    @MCType("Double")
    private double z;
    /** The amount of experience this orb will reward once collected */
    @MCType("Short")
    private short count;

    @Override
    public byte[] encode() throws Exception {
        ByteArrayDataOutput packet = ByteStreams.newDataOutput();
        // Packet ID
        packet.write(ByteUtils.encodeVarInt(packetId));
        packet.write(ByteUtils.encodeVarInt(entityId));
        packet.write(ByteUtils.encodeDouble(x));
        packet.write(ByteUtils.encodeDouble(y));
        packet.write(ByteUtils.encodeDouble(z));
        // The amount of experience this orb will reward once collected
        packet.write(ByteUtils.encodeShort(count));
        return packet.toByteArray();
    }
    @Override
    public void decode(ByteArrayDataInput in) throws Exception {
        // Packet ID
        packetId = StreamUtils.readVarInt(in);
        entityId = StreamUtils.readVarInt(in);
        x = StreamUtils.readDouble(in);
        y = StreamUtils.readDouble(in);
        z = StreamUtils.readDouble(in);
        // The amount of experience this orb will reward once collected
        count = StreamUtils.readShort(in);
    }
    public static class Play_Client_SpawnExperienceOrb_Builder {
        private Play_Client_SpawnExperienceOrb object = new Play_Client_SpawnExperienceOrb();
        /** Packet ID */
        public Play_Client_SpawnExperienceOrb_Builder packetId(int packetId) {
            object.packetId = packetId;
            return this;
        }
        public Play_Client_SpawnExperienceOrb_Builder entityId(int entityId) {
            object.entityId = entityId;
            return this;
        }
        public Play_Client_SpawnExperienceOrb_Builder x(double x) {
            object.x = x;
            return this;
        }
        public Play_Client_SpawnExperienceOrb_Builder y(double y) {
            object.y = y;
            return this;
        }
        public Play_Client_SpawnExperienceOrb_Builder z(double z) {
            object.z = z;
            return this;
        }
        /** The amount of experience this orb will reward once collected */
        public Play_Client_SpawnExperienceOrb_Builder count(short count) {
            object.count = count;
            return this;
        }
        public Play_Client_SpawnExperienceOrb build() {
             return object;
        }

    }
    public static Play_Client_SpawnExperienceOrb_Builder builder() {
        return new Play_Client_SpawnExperienceOrb_Builder();
    }
}