package pub.qiuf.litemc.protocol.play.client;

import pub.qiuf.litemc.common.bean.datatype.Packet;
import com.google.common.io.ByteArrayDataInput;
import com.google.common.io.ByteStreams;
import pub.qiuf.litemc.common.util.ByteUtils;
import pub.qiuf.litemc.common.annotation.MCType;
import com.google.common.io.ByteArrayDataOutput;
import pub.qiuf.litemc.common.bean.datatype.Slot;
import pub.qiuf.litemc.common.annotation.ServerPacket;
import lombok.Data;
import pub.qiuf.litemc.common.util.StreamUtils;

/**
 * Code is generated by <code>pub.qiuf.litemc.generator.ProtocolGenerator</code>, Please don't modify.<br>
 * See more detail from <a>https://wiki.vg/Protocol</a><br>
 */
@Data
@ServerPacket(0x47)
public class Play_Client_EntityEquipment extends Packet {
    /** Packet ID */
    @MCType("VarInt")
    private int packetId = 0x47;
    /** Entity's EID */
    @MCType("VarInt")
    private int entityId;
    /** Equipment slot. 0: main hand, 1: off hand, 2–5: armor slot (2: boots, 3: leggings, 4: chestplate, 5: helmet) */
    @MCType("VarInt")
    private int slot;
    @MCType("Slot")
    private Slot item;

    @Override
    public byte[] encode() throws Exception {
        ByteArrayDataOutput packet = ByteStreams.newDataOutput();
        // Packet ID
        packet.write(ByteUtils.encodeVarInt(packetId));
        // Entity's EID
        packet.write(ByteUtils.encodeVarInt(entityId));
        // Equipment slot. 0: main hand, 1: off hand, 2–5: armor slot (2: boots, 3: leggings, 4: chestplate, 5: helmet)
        packet.write(ByteUtils.encodeVarInt(slot));
        packet.write(ByteUtils.encodeSlot(item));
        return packet.toByteArray();
    }
    @Override
    public void decode(ByteArrayDataInput in) throws Exception {
        // Packet ID
        packetId = StreamUtils.readVarInt(in);
        // Entity's EID
        entityId = StreamUtils.readVarInt(in);
        // Equipment slot. 0: main hand, 1: off hand, 2–5: armor slot (2: boots, 3: leggings, 4: chestplate, 5: helmet)
        slot = StreamUtils.readVarInt(in);
        item = StreamUtils.readSlot(in);
    }
    public static class Play_Client_EntityEquipment_Builder {
        private Play_Client_EntityEquipment object = new Play_Client_EntityEquipment();
        /** Packet ID */
        public Play_Client_EntityEquipment_Builder packetId(int packetId) {
            object.packetId = packetId;
            return this;
        }
        /** Entity's EID */
        public Play_Client_EntityEquipment_Builder entityId(int entityId) {
            object.entityId = entityId;
            return this;
        }
        /** Equipment slot. 0: main hand, 1: off hand, 2–5: armor slot (2: boots, 3: leggings, 4: chestplate, 5: helmet) */
        public Play_Client_EntityEquipment_Builder slot(int slot) {
            object.slot = slot;
            return this;
        }
        public Play_Client_EntityEquipment_Builder item(Slot item) {
            object.item = item;
            return this;
        }
        public Play_Client_EntityEquipment build() {
             return object;
        }

    }
    public static Play_Client_EntityEquipment_Builder builder() {
        return new Play_Client_EntityEquipment_Builder();
    }
}