package pub.qiuf.litemc.protocol.play.client;

import pub.qiuf.litemc.common.bean.datatype.Packet;
import com.google.common.io.ByteArrayDataInput;
import com.google.common.io.ByteStreams;
import pub.qiuf.litemc.common.util.ByteUtils;
import pub.qiuf.litemc.common.annotation.MCType;
import com.google.common.io.ByteArrayDataOutput;
import pub.qiuf.litemc.common.annotation.ServerPacket;
import lombok.Data;
import pub.qiuf.litemc.common.util.StreamUtils;

/**
 * Code is generated by <code>pub.qiuf.litemc.generator.ProtocolGenerator</code>, Please don't modify.<br>
 * See more detail from <a>https://wiki.vg/Protocol</a><br>
 */
@Data
@ServerPacket(0x54)
public class Play_Client_PlayerListHeaderAndFooter extends Packet {
    /** Packet ID */
    @MCType("VarInt")
    private int packetId = 0x54;
    /** To remove the header, send a empty translatable component: {"translate":""} */
    @MCType("Chat")
    private String header;
    /** To remove the footer, send a empty translatable component: {"translate":""} */
    @MCType("Chat")
    private String footer;

    @Override
    public byte[] encode() throws Exception {
        ByteArrayDataOutput packet = ByteStreams.newDataOutput();
        // Packet ID
        packet.write(ByteUtils.encodeVarInt(packetId));
        // To remove the header, send a empty translatable component: {"translate":""}
        packet.write(ByteUtils.encodeChat(header));
        // To remove the footer, send a empty translatable component: {"translate":""}
        packet.write(ByteUtils.encodeChat(footer));
        return packet.toByteArray();
    }
    @Override
    public void decode(ByteArrayDataInput in) throws Exception {
        // Packet ID
        packetId = StreamUtils.readVarInt(in);
        // To remove the header, send a empty translatable component: {"translate":""}
        header = StreamUtils.readChat(in);
        // To remove the footer, send a empty translatable component: {"translate":""}
        footer = StreamUtils.readChat(in);
    }
    public static class Play_Client_PlayerListHeaderAndFooter_Builder {
        private Play_Client_PlayerListHeaderAndFooter object = new Play_Client_PlayerListHeaderAndFooter();
        /** Packet ID */
        public Play_Client_PlayerListHeaderAndFooter_Builder packetId(int packetId) {
            object.packetId = packetId;
            return this;
        }
        /** To remove the header, send a empty translatable component: {"translate":""} */
        public Play_Client_PlayerListHeaderAndFooter_Builder header(String header) {
            object.header = header;
            return this;
        }
        /** To remove the footer, send a empty translatable component: {"translate":""} */
        public Play_Client_PlayerListHeaderAndFooter_Builder footer(String footer) {
            object.footer = footer;
            return this;
        }
        public Play_Client_PlayerListHeaderAndFooter build() {
             return object;
        }

    }
    public static Play_Client_PlayerListHeaderAndFooter_Builder builder() {
        return new Play_Client_PlayerListHeaderAndFooter_Builder();
    }
}