package pub.qiuf.litemc.protocol.play.client;

import pub.qiuf.litemc.common.bean.datatype.Packet;
import com.google.common.io.ByteArrayDataInput;
import com.google.common.io.ByteStreams;
import pub.qiuf.litemc.common.util.ByteUtils;
import pub.qiuf.litemc.common.annotation.MCType;
import com.google.common.io.ByteArrayDataOutput;
import pub.qiuf.litemc.common.annotation.ServerPacket;
import lombok.Data;
import pub.qiuf.litemc.common.util.StreamUtils;

/**
 * Code is generated by <code>pub.qiuf.litemc.generator.ProtocolGenerator</code>, Please don't modify.<br>
 * See more detail from <a>https://wiki.vg/Protocol</a><br>
 */
@Data
@ServerPacket(0x41)
public class Play_Client_UpdateViewPosition extends Packet {
    /** Packet ID */
    @MCType("VarInt")
    private int packetId = 0x41;
    /** Chunk X coordinate of the player's position */
    @MCType("VarInt")
    private int chunkX;
    /** Chunk Z coordinate of the player's position */
    @MCType("VarInt")
    private int chunkZ;

    @Override
    public byte[] encode() throws Exception {
        ByteArrayDataOutput packet = ByteStreams.newDataOutput();
        // Packet ID
        packet.write(ByteUtils.encodeVarInt(packetId));
        // Chunk X coordinate of the player's position
        packet.write(ByteUtils.encodeVarInt(chunkX));
        // Chunk Z coordinate of the player's position
        packet.write(ByteUtils.encodeVarInt(chunkZ));
        return packet.toByteArray();
    }
    @Override
    public void decode(ByteArrayDataInput in) throws Exception {
        // Packet ID
        packetId = StreamUtils.readVarInt(in);
        // Chunk X coordinate of the player's position
        chunkX = StreamUtils.readVarInt(in);
        // Chunk Z coordinate of the player's position
        chunkZ = StreamUtils.readVarInt(in);
    }
    public static class Play_Client_UpdateViewPosition_Builder {
        private Play_Client_UpdateViewPosition object = new Play_Client_UpdateViewPosition();
        /** Packet ID */
        public Play_Client_UpdateViewPosition_Builder packetId(int packetId) {
            object.packetId = packetId;
            return this;
        }
        /** Chunk X coordinate of the player's position */
        public Play_Client_UpdateViewPosition_Builder chunkX(int chunkX) {
            object.chunkX = chunkX;
            return this;
        }
        /** Chunk Z coordinate of the player's position */
        public Play_Client_UpdateViewPosition_Builder chunkZ(int chunkZ) {
            object.chunkZ = chunkZ;
            return this;
        }
        public Play_Client_UpdateViewPosition build() {
             return object;
        }

    }
    public static Play_Client_UpdateViewPosition_Builder builder() {
        return new Play_Client_UpdateViewPosition_Builder();
    }
}