package pub.qiuf.litemc.protocol.play.client;

import pub.qiuf.litemc.common.bean.datatype.Packet;
import com.google.common.io.ByteArrayDataInput;
import com.google.common.io.ByteStreams;
import pub.qiuf.litemc.common.util.ByteUtils;
import pub.qiuf.litemc.common.annotation.MCType;
import com.google.common.io.ByteArrayDataOutput;
import pub.qiuf.litemc.common.annotation.ServerPacket;
import lombok.Data;
import pub.qiuf.litemc.common.util.StreamUtils;

/**
 * Code is generated by <code>pub.qiuf.litemc.generator.ProtocolGenerator</code>, Please don't modify.<br>
 * See more detail from <a>https://wiki.vg/Protocol</a><br>
 */
@Data
@ServerPacket(0x40)
public class Play_Client_HeldItemChange extends Packet {
    /** Packet ID */
    @MCType("VarInt")
    private int packetId = 0x40;
    /** The slot which the player has selected (0–8) */
    @MCType("Byte")
    private byte slot;

    @Override
    public byte[] encode() throws Exception {
        ByteArrayDataOutput packet = ByteStreams.newDataOutput();
        // Packet ID
        packet.write(ByteUtils.encodeVarInt(packetId));
        // The slot which the player has selected (0–8)
        packet.write(ByteUtils.encodeByte(slot));
        return packet.toByteArray();
    }
    @Override
    public void decode(ByteArrayDataInput in) throws Exception {
        // Packet ID
        packetId = StreamUtils.readVarInt(in);
        // The slot which the player has selected (0–8)
        slot = StreamUtils.readByte(in);
    }
    public static class Play_Client_HeldItemChange_Builder {
        private Play_Client_HeldItemChange object = new Play_Client_HeldItemChange();
        /** Packet ID */
        public Play_Client_HeldItemChange_Builder packetId(int packetId) {
            object.packetId = packetId;
            return this;
        }
        /** The slot which the player has selected (0–8) */
        public Play_Client_HeldItemChange_Builder slot(byte slot) {
            object.slot = slot;
            return this;
        }
        public Play_Client_HeldItemChange build() {
             return object;
        }

    }
    public static Play_Client_HeldItemChange_Builder builder() {
        return new Play_Client_HeldItemChange_Builder();
    }
}