package pub.qiuf.litemc.protocol.play.client;

import pub.qiuf.litemc.common.bean.datatype.Packet;
import com.google.common.io.ByteArrayDataInput;
import com.google.common.io.ByteStreams;
import pub.qiuf.litemc.common.util.ByteUtils;
import pub.qiuf.litemc.common.annotation.MCType;
import com.google.common.io.ByteArrayDataOutput;
import pub.qiuf.litemc.common.annotation.ServerPacket;
import lombok.Data;
import pub.qiuf.litemc.common.util.StreamUtils;

/**
 * Code is generated by <code>pub.qiuf.litemc.generator.ProtocolGenerator</code>, Please don't modify.<br>
 * See more detail from <a>https://wiki.vg/Protocol</a><br>
 */
@Data
@ServerPacket(0x42)
public class Play_Client_UpdateViewDistance extends Packet {
    /** Packet ID */
    @MCType("VarInt")
    private int packetId = 0x42;
    /** Render distance (2-32) */
    @MCType("VarInt")
    private int viewDistance;

    @Override
    public byte[] encode() throws Exception {
        ByteArrayDataOutput packet = ByteStreams.newDataOutput();
        // Packet ID
        packet.write(ByteUtils.encodeVarInt(packetId));
        // Render distance (2-32)
        packet.write(ByteUtils.encodeVarInt(viewDistance));
        return packet.toByteArray();
    }
    @Override
    public void decode(ByteArrayDataInput in) throws Exception {
        // Packet ID
        packetId = StreamUtils.readVarInt(in);
        // Render distance (2-32)
        viewDistance = StreamUtils.readVarInt(in);
    }
    public static class Play_Client_UpdateViewDistance_Builder {
        private Play_Client_UpdateViewDistance object = new Play_Client_UpdateViewDistance();
        /** Packet ID */
        public Play_Client_UpdateViewDistance_Builder packetId(int packetId) {
            object.packetId = packetId;
            return this;
        }
        /** Render distance (2-32) */
        public Play_Client_UpdateViewDistance_Builder viewDistance(int viewDistance) {
            object.viewDistance = viewDistance;
            return this;
        }
        public Play_Client_UpdateViewDistance build() {
             return object;
        }

    }
    public static Play_Client_UpdateViewDistance_Builder builder() {
        return new Play_Client_UpdateViewDistance_Builder();
    }
}