package pub.qiuf.litemc.protocol.play.client;

import pub.qiuf.litemc.common.bean.datatype.Packet;
import com.google.common.io.ByteArrayDataInput;
import com.google.common.io.ByteStreams;
import pub.qiuf.litemc.common.util.ByteUtils;
import pub.qiuf.litemc.common.annotation.MCType;
import com.google.common.io.ByteArrayDataOutput;
import pub.qiuf.litemc.common.annotation.ServerPacket;
import lombok.Data;
import pub.qiuf.litemc.common.util.StreamUtils;

/**
 * Code is generated by <code>pub.qiuf.litemc.generator.ProtocolGenerator</code>, Please don't modify.<br>
 * See more detail from <a>https://wiki.vg/Protocol</a><br>
 */
@Data
@ServerPacket(0x3C)
public class Play_Client_EntityHeadLook extends Packet {
    /** Packet ID */
    @MCType("VarInt")
    private int packetId = 0x3C;
    @MCType("VarInt")
    private int entityId;
    /** New angle, not a delta */
    @MCType("Angle")
    private byte headYaw;

    @Override
    public byte[] encode() throws Exception {
        ByteArrayDataOutput packet = ByteStreams.newDataOutput();
        // Packet ID
        packet.write(ByteUtils.encodeVarInt(packetId));
        packet.write(ByteUtils.encodeVarInt(entityId));
        // New angle, not a delta
        packet.write(ByteUtils.encodeAngle(headYaw));
        return packet.toByteArray();
    }
    @Override
    public void decode(ByteArrayDataInput in) throws Exception {
        // Packet ID
        packetId = StreamUtils.readVarInt(in);
        entityId = StreamUtils.readVarInt(in);
        // New angle, not a delta
        headYaw = StreamUtils.readAngle(in);
    }
    public static class Play_Client_EntityHeadLook_Builder {
        private Play_Client_EntityHeadLook object = new Play_Client_EntityHeadLook();
        /** Packet ID */
        public Play_Client_EntityHeadLook_Builder packetId(int packetId) {
            object.packetId = packetId;
            return this;
        }
        public Play_Client_EntityHeadLook_Builder entityId(int entityId) {
            object.entityId = entityId;
            return this;
        }
        /** New angle, not a delta */
        public Play_Client_EntityHeadLook_Builder headYaw(byte headYaw) {
            object.headYaw = headYaw;
            return this;
        }
        public Play_Client_EntityHeadLook build() {
             return object;
        }

    }
    public static Play_Client_EntityHeadLook_Builder builder() {
        return new Play_Client_EntityHeadLook_Builder();
    }
}