package pub.qiuf.litemc.protocol.play.client;

import pub.qiuf.litemc.common.bean.datatype.Packet;
import com.google.common.io.ByteArrayDataInput;
import pub.qiuf.litemc.common.bean.datatype.EntityMetadata;
import com.google.common.io.ByteStreams;
import pub.qiuf.litemc.common.util.ByteUtils;
import pub.qiuf.litemc.common.annotation.MCType;
import com.google.common.io.ByteArrayDataOutput;
import pub.qiuf.litemc.common.annotation.ServerPacket;
import lombok.Data;
import pub.qiuf.litemc.common.util.StreamUtils;

/**
 * Code is generated by <code>pub.qiuf.litemc.generator.ProtocolGenerator</code>, Please don't modify.<br>
 * See more detail from <a>https://wiki.vg/Protocol</a><br>
 */
@Data
@ServerPacket(0x44)
public class Play_Client_EntityMetadata extends Packet {
    /** Packet ID */
    @MCType("VarInt")
    private int packetId = 0x44;
    @MCType("VarInt")
    private int entityId;
    @MCType("EntityMetadata")
    private EntityMetadata metadata;

    @Override
    public byte[] encode() throws Exception {
        ByteArrayDataOutput packet = ByteStreams.newDataOutput();
        // Packet ID
        packet.write(ByteUtils.encodeVarInt(packetId));
        packet.write(ByteUtils.encodeVarInt(entityId));
        packet.write(ByteUtils.encodeEntityMetadata(metadata));
        return packet.toByteArray();
    }
    @Override
    public void decode(ByteArrayDataInput in) throws Exception {
        // Packet ID
        packetId = StreamUtils.readVarInt(in);
        entityId = StreamUtils.readVarInt(in);
        metadata = StreamUtils.readEntityMetadata(in);
    }
    public static class Play_Client_EntityMetadata_Builder {
        private Play_Client_EntityMetadata object = new Play_Client_EntityMetadata();
        /** Packet ID */
        public Play_Client_EntityMetadata_Builder packetId(int packetId) {
            object.packetId = packetId;
            return this;
        }
        public Play_Client_EntityMetadata_Builder entityId(int entityId) {
            object.entityId = entityId;
            return this;
        }
        public Play_Client_EntityMetadata_Builder metadata(EntityMetadata metadata) {
            object.metadata = metadata;
            return this;
        }
        public Play_Client_EntityMetadata build() {
             return object;
        }

    }
    public static Play_Client_EntityMetadata_Builder builder() {
        return new Play_Client_EntityMetadata_Builder();
    }
}