package pub.qiuf.litemc.protocol.play.client;

import pub.qiuf.litemc.common.bean.datatype.Packet;
import com.google.common.io.ByteArrayDataInput;
import com.google.common.io.ByteStreams;
import pub.qiuf.litemc.common.util.ByteUtils;
import pub.qiuf.litemc.common.annotation.MCType;
import com.google.common.io.ByteArrayDataOutput;
import pub.qiuf.litemc.common.annotation.ServerPacket;
import lombok.Data;
import pub.qiuf.litemc.common.util.StreamUtils;

/**
 * Code is generated by <code>pub.qiuf.litemc.generator.ProtocolGenerator</code>, Please don't modify.<br>
 * See more detail from <a>https://wiki.vg/Protocol</a><br>
 */
@Data
@ServerPacket(0x0E)
public class Play_Client_ServerDifficulty extends Packet {
    /** Packet ID */
    @MCType("VarInt")
    private int packetId = 0x0E;
    /** 0: peaceful, 1: easy, 2: normal, 3: hard */
    @MCType("UnsignedByte")
    private int difficulty;
    @MCType("Boolean")
    private boolean difficultyLocked;

    @Override
    public byte[] encode() throws Exception {
        ByteArrayDataOutput packet = ByteStreams.newDataOutput();
        // Packet ID
        packet.write(ByteUtils.encodeVarInt(packetId));
        // 0: peaceful, 1: easy, 2: normal, 3: hard
        packet.write(ByteUtils.encodeUnsignedByte(difficulty));
        packet.write(ByteUtils.encodeBoolean(difficultyLocked));
        return packet.toByteArray();
    }
    @Override
    public void decode(ByteArrayDataInput in) throws Exception {
        // Packet ID
        packetId = StreamUtils.readVarInt(in);
        // 0: peaceful, 1: easy, 2: normal, 3: hard
        difficulty = StreamUtils.readUnsignedByte(in);
        difficultyLocked = StreamUtils.readBoolean(in);
    }
    public static class Play_Client_ServerDifficulty_Builder {
        private Play_Client_ServerDifficulty object = new Play_Client_ServerDifficulty();
        /** Packet ID */
        public Play_Client_ServerDifficulty_Builder packetId(int packetId) {
            object.packetId = packetId;
            return this;
        }
        /** 0: peaceful, 1: easy, 2: normal, 3: hard */
        public Play_Client_ServerDifficulty_Builder difficulty(int difficulty) {
            object.difficulty = difficulty;
            return this;
        }
        public Play_Client_ServerDifficulty_Builder difficultyLocked(boolean difficultyLocked) {
            object.difficultyLocked = difficultyLocked;
            return this;
        }
        public Play_Client_ServerDifficulty build() {
             return object;
        }

    }
    public static Play_Client_ServerDifficulty_Builder builder() {
        return new Play_Client_ServerDifficulty_Builder();
    }
}