package pub.qiuf.litemc.protocol.play.client;

import pub.qiuf.litemc.common.bean.datatype.Packet;
import com.google.common.io.ByteArrayDataInput;
import com.google.common.io.ByteStreams;
import pub.qiuf.litemc.common.util.ByteUtils;
import pub.qiuf.litemc.common.annotation.MCType;
import com.google.common.io.ByteArrayDataOutput;
import pub.qiuf.litemc.common.annotation.ServerPacket;
import lombok.Data;
import pub.qiuf.litemc.common.util.StreamUtils;

/**
 * Code is generated by <code>pub.qiuf.litemc.generator.ProtocolGenerator</code>, Please don't modify.<br>
 * See more detail from <a>https://wiki.vg/Protocol</a><br>
 */
@Data
@ServerPacket(0x2E)
public class Play_Client_OpenBook extends Packet {
    /** Packet ID */
    @MCType("VarInt")
    private int packetId = 0x2E;
    /** 0: Main hand, 1: Off hand */
    @MCType("VarInt")
    private int hand;

    @Override
    public byte[] encode() throws Exception {
        ByteArrayDataOutput packet = ByteStreams.newDataOutput();
        // Packet ID
        packet.write(ByteUtils.encodeVarInt(packetId));
        // 0: Main hand, 1: Off hand
        packet.write(ByteUtils.encodeVarInt(hand));
        return packet.toByteArray();
    }
    @Override
    public void decode(ByteArrayDataInput in) throws Exception {
        // Packet ID
        packetId = StreamUtils.readVarInt(in);
        // 0: Main hand, 1: Off hand
        hand = StreamUtils.readVarInt(in);
    }
    public static class Play_Client_OpenBook_Builder {
        private Play_Client_OpenBook object = new Play_Client_OpenBook();
        /** Packet ID */
        public Play_Client_OpenBook_Builder packetId(int packetId) {
            object.packetId = packetId;
            return this;
        }
        /** 0: Main hand, 1: Off hand */
        public Play_Client_OpenBook_Builder hand(int hand) {
            object.hand = hand;
            return this;
        }
        public Play_Client_OpenBook build() {
             return object;
        }

    }
    public static Play_Client_OpenBook_Builder builder() {
        return new Play_Client_OpenBook_Builder();
    }
}