package pub.qiuf.litemc.protocol.play.client;

import pub.qiuf.litemc.common.bean.datatype.Packet;
import com.google.common.io.ByteArrayDataInput;
import com.google.common.io.ByteStreams;
import pub.qiuf.litemc.common.util.ByteUtils;
import pub.qiuf.litemc.common.annotation.MCType;
import com.google.common.io.ByteArrayDataOutput;
import pub.qiuf.litemc.common.annotation.ServerPacket;
import lombok.Data;
import pub.qiuf.litemc.common.util.StreamUtils;

/**
 * Code is generated by <code>pub.qiuf.litemc.generator.ProtocolGenerator</code>, Please don't modify.<br>
 * See more detail from <a>https://wiki.vg/Protocol</a><br>
 */
@Data
@ServerPacket(0x1F)
public class Play_Client_ChangeGameState extends Packet {
    /** Packet ID */
    @MCType("VarInt")
    private int packetId = 0x1F;
    /** See below */
    @MCType("UnsignedByte")
    private int reason;
    /** Depends on Reason */
    @MCType("Float")
    private float value;

    @Override
    public byte[] encode() throws Exception {
        ByteArrayDataOutput packet = ByteStreams.newDataOutput();
        // Packet ID
        packet.write(ByteUtils.encodeVarInt(packetId));
        // See below
        packet.write(ByteUtils.encodeUnsignedByte(reason));
        // Depends on Reason
        packet.write(ByteUtils.encodeFloat(value));
        return packet.toByteArray();
    }
    @Override
    public void decode(ByteArrayDataInput in) throws Exception {
        // Packet ID
        packetId = StreamUtils.readVarInt(in);
        // See below
        reason = StreamUtils.readUnsignedByte(in);
        // Depends on Reason
        value = StreamUtils.readFloat(in);
    }
    public static class Play_Client_ChangeGameState_Builder {
        private Play_Client_ChangeGameState object = new Play_Client_ChangeGameState();
        /** Packet ID */
        public Play_Client_ChangeGameState_Builder packetId(int packetId) {
            object.packetId = packetId;
            return this;
        }
        /** See below */
        public Play_Client_ChangeGameState_Builder reason(int reason) {
            object.reason = reason;
            return this;
        }
        /** Depends on Reason */
        public Play_Client_ChangeGameState_Builder value(float value) {
            object.value = value;
            return this;
        }
        public Play_Client_ChangeGameState build() {
             return object;
        }

    }
    public static Play_Client_ChangeGameState_Builder builder() {
        return new Play_Client_ChangeGameState_Builder();
    }
}