package pub.qiuf.litemc.protocol.play.client;

import pub.qiuf.litemc.common.bean.datatype.Packet;
import com.google.common.io.ByteArrayDataInput;
import com.google.common.io.ByteStreams;
import pub.qiuf.litemc.common.util.ByteUtils;
import pub.qiuf.litemc.common.annotation.MCType;
import com.google.common.io.ByteArrayDataOutput;
import pub.qiuf.litemc.common.annotation.ServerPacket;
import lombok.Data;
import pub.qiuf.litemc.common.util.StreamUtils;

/**
 * Code is generated by <code>pub.qiuf.litemc.generator.ProtocolGenerator</code>, Please don't modify.<br>
 * See more detail from <a>https://wiki.vg/Protocol</a><br>
 */
@Data
@ServerPacket(0x4B)
public class Play_Client_SetPassengers extends Packet {
    /** Packet ID */
    @MCType("VarInt")
    private int packetId = 0x4B;
    /** Vehicle's EID */
    @MCType("VarInt")
    private int entityId;
    /** Number of elements in the following array */
    @MCType("VarInt")
    private int passengerCount;
    /** EIDs of entity's passengers */
    @MCType("VarInt")
    private int[] passengers;

    @Override
    public byte[] encode() throws Exception {
        ByteArrayDataOutput packet = ByteStreams.newDataOutput();
        // Packet ID
        packet.write(ByteUtils.encodeVarInt(packetId));
        // Vehicle's EID
        packet.write(ByteUtils.encodeVarInt(entityId));
        // Number of elements in the following array
        packet.write(ByteUtils.encodeVarInt(passengerCount));
        // EIDs of entity's passengers
        for (int temp : passengers) {
            packet.write(ByteUtils.encodeInt(temp));
        }
        return packet.toByteArray();
    }
    @Override
    public void decode(ByteArrayDataInput in) throws Exception {
        // Packet ID
        packetId = StreamUtils.readVarInt(in);
        // Vehicle's EID
        entityId = StreamUtils.readVarInt(in);
        // Number of elements in the following array
        passengerCount = StreamUtils.readVarInt(in);
        // EIDs of entity's passengers
        passengers = new int[passengerCount];
        for (int i = 0; i < passengers.length; i++) {
            passengers[i] = StreamUtils.readVarInt(in);
        }
    }
    public static class Play_Client_SetPassengers_Builder {
        private Play_Client_SetPassengers object = new Play_Client_SetPassengers();
        /** Packet ID */
        public Play_Client_SetPassengers_Builder packetId(int packetId) {
            object.packetId = packetId;
            return this;
        }
        /** Vehicle's EID */
        public Play_Client_SetPassengers_Builder entityId(int entityId) {
            object.entityId = entityId;
            return this;
        }
        /** Number of elements in the following array */
        public Play_Client_SetPassengers_Builder passengerCount(int passengerCount) {
            object.passengerCount = passengerCount;
            return this;
        }
        /** EIDs of entity's passengers */
        public Play_Client_SetPassengers_Builder passengers(int[] passengers) {
            object.passengers = passengers;
            return this;
        }
        public Play_Client_SetPassengers build() {
             return object;
        }

    }
    public static Play_Client_SetPassengers_Builder builder() {
        return new Play_Client_SetPassengers_Builder();
    }
}