package pub.qiuf.litemc.protocol.play.client;

import pub.qiuf.litemc.common.bean.datatype.Packet;
import com.google.common.io.ByteArrayDataInput;
import com.google.common.io.ByteStreams;
import pub.qiuf.litemc.common.util.ByteUtils;
import pub.qiuf.litemc.common.annotation.MCType;
import com.google.common.io.ByteArrayDataOutput;
import pub.qiuf.litemc.common.annotation.ServerPacket;
import lombok.Data;
import pub.qiuf.litemc.common.util.StreamUtils;

/**
 * Code is generated by <code>pub.qiuf.litemc.generator.ProtocolGenerator</code>, Please don't modify.<br>
 * See more detail from <a>https://wiki.vg/Protocol</a><br>
 */
@Data
@ServerPacket(0x32)
public class Play_Client_PlayerAbilities extends Packet {
    /** Packet ID */
    @MCType("VarInt")
    private int packetId = 0x32;
    /** Bit field, see below */
    @MCType("Byte")
    private byte flags;
    /** 0.05 by default */
    @MCType("Float")
    private float flyingSpeed;
    /** Modifies the field of view, like a speed potion. A Notchian server will use the same value as the movement speed sent in the Entity Properties packet, which defaults to 0.1 for players. */
    @MCType("Float")
    private float fieldOfViewModifier;

    @Override
    public byte[] encode() throws Exception {
        ByteArrayDataOutput packet = ByteStreams.newDataOutput();
        // Packet ID
        packet.write(ByteUtils.encodeVarInt(packetId));
        // Bit field, see below
        packet.write(ByteUtils.encodeByte(flags));
        // 0.05 by default
        packet.write(ByteUtils.encodeFloat(flyingSpeed));
        // Modifies the field of view, like a speed potion. A Notchian server will use the same value as the movement speed sent in the Entity Properties packet, which defaults to 0.1 for players.
        packet.write(ByteUtils.encodeFloat(fieldOfViewModifier));
        return packet.toByteArray();
    }
    @Override
    public void decode(ByteArrayDataInput in) throws Exception {
        // Packet ID
        packetId = StreamUtils.readVarInt(in);
        // Bit field, see below
        flags = StreamUtils.readByte(in);
        // 0.05 by default
        flyingSpeed = StreamUtils.readFloat(in);
        // Modifies the field of view, like a speed potion. A Notchian server will use the same value as the movement speed sent in the Entity Properties packet, which defaults to 0.1 for players.
        fieldOfViewModifier = StreamUtils.readFloat(in);
    }
    public static class Play_Client_PlayerAbilities_Builder {
        private Play_Client_PlayerAbilities object = new Play_Client_PlayerAbilities();
        /** Packet ID */
        public Play_Client_PlayerAbilities_Builder packetId(int packetId) {
            object.packetId = packetId;
            return this;
        }
        /** Bit field, see below */
        public Play_Client_PlayerAbilities_Builder flags(byte flags) {
            object.flags = flags;
            return this;
        }
        /** 0.05 by default */
        public Play_Client_PlayerAbilities_Builder flyingSpeed(float flyingSpeed) {
            object.flyingSpeed = flyingSpeed;
            return this;
        }
        /** Modifies the field of view, like a speed potion. A Notchian server will use the same value as the movement speed sent in the Entity Properties packet, which defaults to 0.1 for players. */
        public Play_Client_PlayerAbilities_Builder fieldOfViewModifier(float fieldOfViewModifier) {
            object.fieldOfViewModifier = fieldOfViewModifier;
            return this;
        }
        public Play_Client_PlayerAbilities build() {
             return object;
        }

    }
    public static Play_Client_PlayerAbilities_Builder builder() {
        return new Play_Client_PlayerAbilities_Builder();
    }
}