package pub.qiuf.litemc.protocol.play.client;

import pub.qiuf.litemc.common.bean.datatype.Packet;
import com.google.common.io.ByteArrayDataInput;
import com.google.common.io.ByteStreams;
import pub.qiuf.litemc.common.util.ByteUtils;
import pub.qiuf.litemc.common.annotation.MCType;
import com.google.common.io.ByteArrayDataOutput;
import pub.qiuf.litemc.common.annotation.ServerPacket;
import lombok.Data;
import pub.qiuf.litemc.common.util.StreamUtils;

/**
 * Code is generated by <code>pub.qiuf.litemc.generator.ProtocolGenerator</code>, Please don't modify.<br>
 * See more detail from <a>https://wiki.vg/Protocol</a><br>
 */
@Data
@ServerPacket(0x56)
public class Play_Client_CollectItem extends Packet {
    /** Packet ID */
    @MCType("VarInt")
    private int packetId = 0x56;
    @MCType("VarInt")
    private int collectedEntityId;
    @MCType("VarInt")
    private int collectorEntityId;
    /** Seems to be 1 for XP orbs, otherwise the number of items in the stack. */
    @MCType("VarInt")
    private int pickupItemCount;

    @Override
    public byte[] encode() throws Exception {
        ByteArrayDataOutput packet = ByteStreams.newDataOutput();
        // Packet ID
        packet.write(ByteUtils.encodeVarInt(packetId));
        packet.write(ByteUtils.encodeVarInt(collectedEntityId));
        packet.write(ByteUtils.encodeVarInt(collectorEntityId));
        // Seems to be 1 for XP orbs, otherwise the number of items in the stack.
        packet.write(ByteUtils.encodeVarInt(pickupItemCount));
        return packet.toByteArray();
    }
    @Override
    public void decode(ByteArrayDataInput in) throws Exception {
        // Packet ID
        packetId = StreamUtils.readVarInt(in);
        collectedEntityId = StreamUtils.readVarInt(in);
        collectorEntityId = StreamUtils.readVarInt(in);
        // Seems to be 1 for XP orbs, otherwise the number of items in the stack.
        pickupItemCount = StreamUtils.readVarInt(in);
    }
    public static class Play_Client_CollectItem_Builder {
        private Play_Client_CollectItem object = new Play_Client_CollectItem();
        /** Packet ID */
        public Play_Client_CollectItem_Builder packetId(int packetId) {
            object.packetId = packetId;
            return this;
        }
        public Play_Client_CollectItem_Builder collectedEntityId(int collectedEntityId) {
            object.collectedEntityId = collectedEntityId;
            return this;
        }
        public Play_Client_CollectItem_Builder collectorEntityId(int collectorEntityId) {
            object.collectorEntityId = collectorEntityId;
            return this;
        }
        /** Seems to be 1 for XP orbs, otherwise the number of items in the stack. */
        public Play_Client_CollectItem_Builder pickupItemCount(int pickupItemCount) {
            object.pickupItemCount = pickupItemCount;
            return this;
        }
        public Play_Client_CollectItem build() {
             return object;
        }

    }
    public static Play_Client_CollectItem_Builder builder() {
        return new Play_Client_CollectItem_Builder();
    }
}