package pub.qiuf.litemc.protocol.play.client;

import pub.qiuf.litemc.common.bean.datatype.Packet;
import com.google.common.io.ByteArrayDataInput;
import com.google.common.io.ByteStreams;
import pub.qiuf.litemc.common.util.ByteUtils;
import pub.qiuf.litemc.common.annotation.MCType;
import com.google.common.io.ByteArrayDataOutput;
import pub.qiuf.litemc.common.annotation.ServerPacket;
import lombok.Data;
import pub.qiuf.litemc.common.util.StreamUtils;

/**
 * Code is generated by <code>pub.qiuf.litemc.generator.ProtocolGenerator</code>, Please don't modify.<br>
 * See more detail from <a>https://wiki.vg/Protocol</a><br>
 */
@Data
@ServerPacket(0x1E)
public class Play_Client_UnloadChunk extends Packet {
    /** Packet ID */
    @MCType("VarInt")
    private int packetId = 0x1E;
    /** Block coordinate divided by 16, rounded down */
    @MCType("Int")
    private int chunkX;
    /** Block coordinate divided by 16, rounded down */
    @MCType("Int")
    private int chunkZ;

    @Override
    public byte[] encode() throws Exception {
        ByteArrayDataOutput packet = ByteStreams.newDataOutput();
        // Packet ID
        packet.write(ByteUtils.encodeVarInt(packetId));
        // Block coordinate divided by 16, rounded down
        packet.write(ByteUtils.encodeInt(chunkX));
        // Block coordinate divided by 16, rounded down
        packet.write(ByteUtils.encodeInt(chunkZ));
        return packet.toByteArray();
    }
    @Override
    public void decode(ByteArrayDataInput in) throws Exception {
        // Packet ID
        packetId = StreamUtils.readVarInt(in);
        // Block coordinate divided by 16, rounded down
        chunkX = StreamUtils.readInt(in);
        // Block coordinate divided by 16, rounded down
        chunkZ = StreamUtils.readInt(in);
    }
    public static class Play_Client_UnloadChunk_Builder {
        private Play_Client_UnloadChunk object = new Play_Client_UnloadChunk();
        /** Packet ID */
        public Play_Client_UnloadChunk_Builder packetId(int packetId) {
            object.packetId = packetId;
            return this;
        }
        /** Block coordinate divided by 16, rounded down */
        public Play_Client_UnloadChunk_Builder chunkX(int chunkX) {
            object.chunkX = chunkX;
            return this;
        }
        /** Block coordinate divided by 16, rounded down */
        public Play_Client_UnloadChunk_Builder chunkZ(int chunkZ) {
            object.chunkZ = chunkZ;
            return this;
        }
        public Play_Client_UnloadChunk build() {
             return object;
        }

    }
    public static Play_Client_UnloadChunk_Builder builder() {
        return new Play_Client_UnloadChunk_Builder();
    }
}