package pub.qiuf.litemc.protocol.play.client;

import pub.qiuf.litemc.common.bean.datatype.Packet;
import com.google.common.io.ByteArrayDataInput;
import com.google.common.io.ByteStreams;
import pub.qiuf.litemc.common.util.ByteUtils;
import pub.qiuf.litemc.common.annotation.MCType;
import com.google.common.io.ByteArrayDataOutput;
import pub.qiuf.litemc.common.annotation.ServerPacket;
import lombok.Data;
import pub.qiuf.litemc.common.util.StreamUtils;

/**
 * Code is generated by <code>pub.qiuf.litemc.generator.ProtocolGenerator</code>, Please don't modify.<br>
 * See more detail from <a>https://wiki.vg/Protocol</a><br>
 */
@Data
@ServerPacket(0x07)
public class Play_Client_Statistics extends Packet {
    /** Packet ID */
    @MCType("VarInt")
    private int packetId = 0x07;
    /** Number of elements in the following array */
    @MCType("VarInt")
    private int count;
    @MCType("Play_Client_Statistics_Statistic")
    private Play_Client_Statistics_Statistic[] statistic;

    @Override
    public byte[] encode() throws Exception {
        ByteArrayDataOutput packet = ByteStreams.newDataOutput();
        // Packet ID
        packet.write(ByteUtils.encodeVarInt(packetId));
        // Number of elements in the following array
        packet.write(ByteUtils.encodeVarInt(count));
        for (Play_Client_Statistics_Statistic temp : statistic) {
            packet.write(temp.encode());
        }
        return packet.toByteArray();
    }
    @Override
    public void decode(ByteArrayDataInput in) throws Exception {
        // Packet ID
        packetId = StreamUtils.readVarInt(in);
        // Number of elements in the following array
        count = StreamUtils.readVarInt(in);
        statistic = new Play_Client_Statistics_Statistic[count];
        for (int i = 0; i < statistic.length; i++) {
            statistic[i] = new Play_Client_Statistics_Statistic();
            statistic[i].decode(in);
        }
    }
    @Data
    public static class Play_Client_Statistics_Statistic extends Packet {
        /** See below */
        @MCType("VarInt")
        private int categoryId;
        /** See below */
        @MCType("VarInt")
        private int statisticId;
        /** The amount to set it to */
        @MCType("VarInt")
        private int value;

        @Override
        public byte[] encode() throws Exception {
            ByteArrayDataOutput packet = ByteStreams.newDataOutput();
            // See below
            packet.write(ByteUtils.encodeVarInt(categoryId));
            // See below
            packet.write(ByteUtils.encodeVarInt(statisticId));
            // The amount to set it to
            packet.write(ByteUtils.encodeVarInt(value));
            return packet.toByteArray();
        }
        @Override
        public void decode(ByteArrayDataInput in) throws Exception {
            // See below
            categoryId = StreamUtils.readVarInt(in);
            // See below
            statisticId = StreamUtils.readVarInt(in);
            // The amount to set it to
            value = StreamUtils.readVarInt(in);
        }
    }
    @FunctionalInterface
    public interface Play_Client_Statistics_Statistic_Provider {
        Play_Client_Statistics_Statistic[] provide();
    }
    public static Play_Client_Statistics_Statistic_Builder statisticBuilder() {
        return new Play_Client_Statistics_Statistic_Builder();
    }
    public static class Play_Client_Statistics_Statistic_Builder {
        private Play_Client_Statistics_Statistic object = new Play_Client_Statistics_Statistic();
        /** See below */
        public Play_Client_Statistics_Statistic_Builder categoryId(int categoryId) {
            object.categoryId = categoryId;
            return this;
        }
        /** See below */
        public Play_Client_Statistics_Statistic_Builder statisticId(int statisticId) {
            object.statisticId = statisticId;
            return this;
        }
        /** The amount to set it to */
        public Play_Client_Statistics_Statistic_Builder value(int value) {
            object.value = value;
            return this;
        }
        public Play_Client_Statistics_Statistic build() {
             return object;
        }

    }
    public static class Play_Client_Statistics_Builder {
        private Play_Client_Statistics object = new Play_Client_Statistics();
        /** Packet ID */
        public Play_Client_Statistics_Builder packetId(int packetId) {
            object.packetId = packetId;
            return this;
        }
        /** Number of elements in the following array */
        public Play_Client_Statistics_Builder count(int count) {
            object.count = count;
            return this;
        }
        public Play_Client_Statistics_Builder statistic(Play_Client_Statistics_Statistic_Provider provider) {
            object.statistic = provider.provide();
            return this;
        }
        public Play_Client_Statistics build() {
             return object;
        }

    }
    public static Play_Client_Statistics_Builder builder() {
        return new Play_Client_Statistics_Builder();
    }
}