package pub.qiuf.litemc.protocol.play.client;

import pub.qiuf.litemc.common.bean.datatype.Packet;
import com.google.common.io.ByteArrayDataInput;
import com.google.common.io.ByteStreams;
import pub.qiuf.litemc.common.util.ByteUtils;
import pub.qiuf.litemc.common.annotation.MCType;
import com.google.common.io.ByteArrayDataOutput;
import pub.qiuf.litemc.common.annotation.ServerPacket;
import lombok.Data;
import pub.qiuf.litemc.common.util.StreamUtils;

/**
 * Code is generated by <code>pub.qiuf.litemc.generator.ProtocolGenerator</code>, Please don't modify.<br>
 * See more detail from <a>https://wiki.vg/Protocol</a><br>
 */
@Data
@ServerPacket(0x31)
public class Play_Client_CraftRecipeResponse extends Packet {
    /** Packet ID */
    @MCType("VarInt")
    private int packetId = 0x31;
    @MCType("Byte")
    private byte windowId;
    /** A recipe ID */
    @MCType("Identifier")
    private String recipe;

    @Override
    public byte[] encode() throws Exception {
        ByteArrayDataOutput packet = ByteStreams.newDataOutput();
        // Packet ID
        packet.write(ByteUtils.encodeVarInt(packetId));
        packet.write(ByteUtils.encodeByte(windowId));
        // A recipe ID
        packet.write(ByteUtils.encodeIdentifier(recipe));
        return packet.toByteArray();
    }
    @Override
    public void decode(ByteArrayDataInput in) throws Exception {
        // Packet ID
        packetId = StreamUtils.readVarInt(in);
        windowId = StreamUtils.readByte(in);
        // A recipe ID
        recipe = StreamUtils.readIdentifier(in);
    }
    public static class Play_Client_CraftRecipeResponse_Builder {
        private Play_Client_CraftRecipeResponse object = new Play_Client_CraftRecipeResponse();
        /** Packet ID */
        public Play_Client_CraftRecipeResponse_Builder packetId(int packetId) {
            object.packetId = packetId;
            return this;
        }
        public Play_Client_CraftRecipeResponse_Builder windowId(byte windowId) {
            object.windowId = windowId;
            return this;
        }
        /** A recipe ID */
        public Play_Client_CraftRecipeResponse_Builder recipe(String recipe) {
            object.recipe = recipe;
            return this;
        }
        public Play_Client_CraftRecipeResponse build() {
             return object;
        }

    }
    public static Play_Client_CraftRecipeResponse_Builder builder() {
        return new Play_Client_CraftRecipeResponse_Builder();
    }
}