package pub.qiuf.litemc.protocol.play.client;

import pub.qiuf.litemc.common.bean.datatype.Packet;
import com.google.common.io.ByteArrayDataInput;
import com.google.common.io.ByteStreams;
import pub.qiuf.litemc.common.util.ByteUtils;
import pub.qiuf.litemc.common.annotation.MCType;
import com.google.common.io.ByteArrayDataOutput;
import pub.qiuf.litemc.common.annotation.ServerPacket;
import lombok.Data;
import pub.qiuf.litemc.common.util.StreamUtils;

/**
 * Code is generated by <code>pub.qiuf.litemc.generator.ProtocolGenerator</code>, Please don't modify.<br>
 * See more detail from <a>https://wiki.vg/Protocol</a><br>
 */
@Data
@ServerPacket(0x1B)
public class Play_Client_Disconnect extends Packet {
    /** Packet ID */
    @MCType("VarInt")
    private int packetId = 0x1B;
    /** Displayed to the client when the connection terminates. */
    @MCType("Chat")
    private String reason;

    @Override
    public byte[] encode() throws Exception {
        ByteArrayDataOutput packet = ByteStreams.newDataOutput();
        // Packet ID
        packet.write(ByteUtils.encodeVarInt(packetId));
        // Displayed to the client when the connection terminates.
        packet.write(ByteUtils.encodeChat(reason));
        return packet.toByteArray();
    }
    @Override
    public void decode(ByteArrayDataInput in) throws Exception {
        // Packet ID
        packetId = StreamUtils.readVarInt(in);
        // Displayed to the client when the connection terminates.
        reason = StreamUtils.readChat(in);
    }
    public static class Play_Client_Disconnect_Builder {
        private Play_Client_Disconnect object = new Play_Client_Disconnect();
        /** Packet ID */
        public Play_Client_Disconnect_Builder packetId(int packetId) {
            object.packetId = packetId;
            return this;
        }
        /** Displayed to the client when the connection terminates. */
        public Play_Client_Disconnect_Builder reason(String reason) {
            object.reason = reason;
            return this;
        }
        public Play_Client_Disconnect build() {
             return object;
        }

    }
    public static Play_Client_Disconnect_Builder builder() {
        return new Play_Client_Disconnect_Builder();
    }
}