package pub.qiuf.litemc.protocol.play.client;

import pub.qiuf.litemc.common.bean.datatype.Packet;
import com.google.common.io.ByteArrayDataInput;
import com.google.common.io.ByteStreams;
import pub.qiuf.litemc.common.util.ByteUtils;
import pub.qiuf.litemc.common.annotation.MCType;
import com.google.common.io.ByteArrayDataOutput;
import pub.qiuf.litemc.common.annotation.ServerPacket;
import lombok.Data;
import pub.qiuf.litemc.common.util.StreamUtils;

/**
 * Code is generated by <code>pub.qiuf.litemc.generator.ProtocolGenerator</code>, Please don't modify.<br>
 * See more detail from <a>https://wiki.vg/Protocol</a><br>
 */
@Data
@ServerPacket(0x05)
public class Play_Client_SpawnPlayer extends Packet {
    /** Packet ID */
    @MCType("VarInt")
    private int packetId = 0x05;
    /** Player's EID */
    @MCType("VarInt")
    private int entityId;
    /** See below for notes on offline mode and NPCs */
    @MCType("UUID")
    private long[] playerUuid = new long[2];
    @MCType("Double")
    private double x;
    @MCType("Double")
    private double y;
    @MCType("Double")
    private double z;
    @MCType("Angle")
    private byte yaw;
    @MCType("Angle")
    private byte pitch;

    @Override
    public byte[] encode() throws Exception {
        ByteArrayDataOutput packet = ByteStreams.newDataOutput();
        // Packet ID
        packet.write(ByteUtils.encodeVarInt(packetId));
        // Player's EID
        packet.write(ByteUtils.encodeVarInt(entityId));
        // See below for notes on offline mode and NPCs
        for (long temp : playerUuid) {
            packet.write(ByteUtils.encodeLong(temp));
        }
        packet.write(ByteUtils.encodeDouble(x));
        packet.write(ByteUtils.encodeDouble(y));
        packet.write(ByteUtils.encodeDouble(z));
        packet.write(ByteUtils.encodeAngle(yaw));
        packet.write(ByteUtils.encodeAngle(pitch));
        return packet.toByteArray();
    }
    @Override
    public void decode(ByteArrayDataInput in) throws Exception {
        // Packet ID
        packetId = StreamUtils.readVarInt(in);
        // Player's EID
        entityId = StreamUtils.readVarInt(in);
        // See below for notes on offline mode and NPCs
        // TODO decode playerUuid
        x = StreamUtils.readDouble(in);
        y = StreamUtils.readDouble(in);
        z = StreamUtils.readDouble(in);
        yaw = StreamUtils.readAngle(in);
        pitch = StreamUtils.readAngle(in);
    }
    public static class Play_Client_SpawnPlayer_Builder {
        private Play_Client_SpawnPlayer object = new Play_Client_SpawnPlayer();
        /** Packet ID */
        public Play_Client_SpawnPlayer_Builder packetId(int packetId) {
            object.packetId = packetId;
            return this;
        }
        /** Player's EID */
        public Play_Client_SpawnPlayer_Builder entityId(int entityId) {
            object.entityId = entityId;
            return this;
        }
        /** See below for notes on offline mode and NPCs */
        public Play_Client_SpawnPlayer_Builder playerUuid(long[] playerUuid) {
            object.playerUuid = playerUuid;
            return this;
        }
        public Play_Client_SpawnPlayer_Builder x(double x) {
            object.x = x;
            return this;
        }
        public Play_Client_SpawnPlayer_Builder y(double y) {
            object.y = y;
            return this;
        }
        public Play_Client_SpawnPlayer_Builder z(double z) {
            object.z = z;
            return this;
        }
        public Play_Client_SpawnPlayer_Builder yaw(byte yaw) {
            object.yaw = yaw;
            return this;
        }
        public Play_Client_SpawnPlayer_Builder pitch(byte pitch) {
            object.pitch = pitch;
            return this;
        }
        public Play_Client_SpawnPlayer build() {
             return object;
        }

    }
    public static Play_Client_SpawnPlayer_Builder builder() {
        return new Play_Client_SpawnPlayer_Builder();
    }
}