package pub.qiuf.litemc.protocol.play.client;

import pub.qiuf.litemc.common.bean.datatype.Packet;
import com.google.common.io.ByteArrayDataInput;
import com.google.common.io.ByteStreams;
import pub.qiuf.litemc.common.util.ByteUtils;
import pub.qiuf.litemc.common.annotation.MCType;
import com.google.common.io.ByteArrayDataOutput;
import pub.qiuf.litemc.common.annotation.ServerPacket;
import lombok.Data;
import pub.qiuf.litemc.common.util.StreamUtils;

/**
 * Code is generated by <code>pub.qiuf.litemc.generator.ProtocolGenerator</code>, Please don't modify.<br>
 * See more detail from <a>https://wiki.vg/Protocol</a><br>
 */
@Data
@ServerPacket(0x1C)
public class Play_Client_EntityStatus extends Packet {
    /** Packet ID */
    @MCType("VarInt")
    private int packetId = 0x1C;
    @MCType("Int")
    private int entityId;
    /** See below */
    @MCType("Byte")
    private byte entityStatus;

    @Override
    public byte[] encode() throws Exception {
        ByteArrayDataOutput packet = ByteStreams.newDataOutput();
        // Packet ID
        packet.write(ByteUtils.encodeVarInt(packetId));
        packet.write(ByteUtils.encodeInt(entityId));
        // See below
        packet.write(ByteUtils.encodeByte(entityStatus));
        return packet.toByteArray();
    }
    @Override
    public void decode(ByteArrayDataInput in) throws Exception {
        // Packet ID
        packetId = StreamUtils.readVarInt(in);
        entityId = StreamUtils.readInt(in);
        // See below
        entityStatus = StreamUtils.readByte(in);
    }
    public static class Play_Client_EntityStatus_Builder {
        private Play_Client_EntityStatus object = new Play_Client_EntityStatus();
        /** Packet ID */
        public Play_Client_EntityStatus_Builder packetId(int packetId) {
            object.packetId = packetId;
            return this;
        }
        public Play_Client_EntityStatus_Builder entityId(int entityId) {
            object.entityId = entityId;
            return this;
        }
        /** See below */
        public Play_Client_EntityStatus_Builder entityStatus(byte entityStatus) {
            object.entityStatus = entityStatus;
            return this;
        }
        public Play_Client_EntityStatus build() {
             return object;
        }

    }
    public static Play_Client_EntityStatus_Builder builder() {
        return new Play_Client_EntityStatus_Builder();
    }
}