package pub.qiuf.litemc.protocol.play.client;

import pub.qiuf.litemc.common.bean.datatype.Packet;
import com.google.common.io.ByteArrayDataInput;
import com.google.common.io.ByteStreams;
import pub.qiuf.litemc.common.util.ByteUtils;
import pub.qiuf.litemc.common.annotation.MCType;
import com.google.common.io.ByteArrayDataOutput;
import pub.qiuf.litemc.common.annotation.ServerPacket;
import lombok.Data;
import pub.qiuf.litemc.common.util.StreamUtils;

/**
 * Code is generated by <code>pub.qiuf.litemc.generator.ProtocolGenerator</code>, Please don't modify.<br>
 * See more detail from <a>https://wiki.vg/Protocol</a><br>
 */
@Data
@ServerPacket(0x18)
public class Play_Client_SetCooldown extends Packet {
    /** Packet ID */
    @MCType("VarInt")
    private int packetId = 0x18;
    /** Numeric ID of the item to apply a cooldown to. */
    @MCType("VarInt")
    private int itemId;
    /** Number of ticks to apply a cooldown for, or 0 to clear the cooldown. */
    @MCType("VarInt")
    private int cooldownTicks;

    @Override
    public byte[] encode() throws Exception {
        ByteArrayDataOutput packet = ByteStreams.newDataOutput();
        // Packet ID
        packet.write(ByteUtils.encodeVarInt(packetId));
        // Numeric ID of the item to apply a cooldown to.
        packet.write(ByteUtils.encodeVarInt(itemId));
        // Number of ticks to apply a cooldown for, or 0 to clear the cooldown.
        packet.write(ByteUtils.encodeVarInt(cooldownTicks));
        return packet.toByteArray();
    }
    @Override
    public void decode(ByteArrayDataInput in) throws Exception {
        // Packet ID
        packetId = StreamUtils.readVarInt(in);
        // Numeric ID of the item to apply a cooldown to.
        itemId = StreamUtils.readVarInt(in);
        // Number of ticks to apply a cooldown for, or 0 to clear the cooldown.
        cooldownTicks = StreamUtils.readVarInt(in);
    }
    public static class Play_Client_SetCooldown_Builder {
        private Play_Client_SetCooldown object = new Play_Client_SetCooldown();
        /** Packet ID */
        public Play_Client_SetCooldown_Builder packetId(int packetId) {
            object.packetId = packetId;
            return this;
        }
        /** Numeric ID of the item to apply a cooldown to. */
        public Play_Client_SetCooldown_Builder itemId(int itemId) {
            object.itemId = itemId;
            return this;
        }
        /** Number of ticks to apply a cooldown for, or 0 to clear the cooldown. */
        public Play_Client_SetCooldown_Builder cooldownTicks(int cooldownTicks) {
            object.cooldownTicks = cooldownTicks;
            return this;
        }
        public Play_Client_SetCooldown build() {
             return object;
        }

    }
    public static Play_Client_SetCooldown_Builder builder() {
        return new Play_Client_SetCooldown_Builder();
    }
}