package pub.qiuf.litemc.protocol.play.client;

import pub.qiuf.litemc.common.bean.datatype.Packet;
import com.google.common.io.ByteArrayDataInput;
import com.google.common.io.ByteStreams;
import pub.qiuf.litemc.common.util.ByteUtils;
import pub.qiuf.litemc.common.annotation.MCType;
import com.google.common.io.ByteArrayDataOutput;
import pub.qiuf.litemc.common.annotation.ServerPacket;
import lombok.Data;
import pub.qiuf.litemc.common.util.StreamUtils;

/**
 * Code is generated by <code>pub.qiuf.litemc.generator.ProtocolGenerator</code>, Please don't modify.<br>
 * See more detail from <a>https://wiki.vg/Protocol</a><br>
 */
@Data
@ServerPacket(0x06)
public class Play_Client_EntityAnimation extends Packet {
    /** Packet ID */
    @MCType("VarInt")
    private int packetId = 0x06;
    /** Player ID */
    @MCType("VarInt")
    private int entityId;
    /** Animation ID (see below) */
    @MCType("UnsignedByte")
    private int animation;

    @Override
    public byte[] encode() throws Exception {
        ByteArrayDataOutput packet = ByteStreams.newDataOutput();
        // Packet ID
        packet.write(ByteUtils.encodeVarInt(packetId));
        // Player ID
        packet.write(ByteUtils.encodeVarInt(entityId));
        // Animation ID (see below)
        packet.write(ByteUtils.encodeUnsignedByte(animation));
        return packet.toByteArray();
    }
    @Override
    public void decode(ByteArrayDataInput in) throws Exception {
        // Packet ID
        packetId = StreamUtils.readVarInt(in);
        // Player ID
        entityId = StreamUtils.readVarInt(in);
        // Animation ID (see below)
        animation = StreamUtils.readUnsignedByte(in);
    }
    public static class Play_Client_EntityAnimation_Builder {
        private Play_Client_EntityAnimation object = new Play_Client_EntityAnimation();
        /** Packet ID */
        public Play_Client_EntityAnimation_Builder packetId(int packetId) {
            object.packetId = packetId;
            return this;
        }
        /** Player ID */
        public Play_Client_EntityAnimation_Builder entityId(int entityId) {
            object.entityId = entityId;
            return this;
        }
        /** Animation ID (see below) */
        public Play_Client_EntityAnimation_Builder animation(int animation) {
            object.animation = animation;
            return this;
        }
        public Play_Client_EntityAnimation build() {
             return object;
        }

    }
    public static Play_Client_EntityAnimation_Builder builder() {
        return new Play_Client_EntityAnimation_Builder();
    }
}