package pub.qiuf.litemc.protocol.play.client;

import pub.qiuf.litemc.common.bean.datatype.Packet;
import com.google.common.io.ByteArrayDataInput;
import com.google.common.io.ByteStreams;
import pub.qiuf.litemc.common.util.ByteUtils;
import pub.qiuf.litemc.common.annotation.MCType;
import com.google.common.io.ByteArrayDataOutput;
import pub.qiuf.litemc.common.annotation.ServerPacket;
import lombok.Data;
import pub.qiuf.litemc.common.util.StreamUtils;

/**
 * Code is generated by <code>pub.qiuf.litemc.generator.ProtocolGenerator</code>, Please don't modify.<br>
 * See more detail from <a>https://wiki.vg/Protocol</a><br>
 */
@Data
@ServerPacket(0x38)
public class Play_Client_DestroyEntities extends Packet {
    /** Packet ID */
    @MCType("VarInt")
    private int packetId = 0x38;
    /** Number of elements in the following array */
    @MCType("VarInt")
    private int count;
    /** The list of entities of destroy */
    @MCType("VarInt")
    private int[] entityIds;

    @Override
    public byte[] encode() throws Exception {
        ByteArrayDataOutput packet = ByteStreams.newDataOutput();
        // Packet ID
        packet.write(ByteUtils.encodeVarInt(packetId));
        // Number of elements in the following array
        packet.write(ByteUtils.encodeVarInt(count));
        // The list of entities of destroy
        for (int temp : entityIds) {
            packet.write(ByteUtils.encodeInt(temp));
        }
        return packet.toByteArray();
    }
    @Override
    public void decode(ByteArrayDataInput in) throws Exception {
        // Packet ID
        packetId = StreamUtils.readVarInt(in);
        // Number of elements in the following array
        count = StreamUtils.readVarInt(in);
        // The list of entities of destroy
        entityIds = new int[count];
        for (int i = 0; i < entityIds.length; i++) {
            entityIds[i] = StreamUtils.readVarInt(in);
        }
    }
    public static class Play_Client_DestroyEntities_Builder {
        private Play_Client_DestroyEntities object = new Play_Client_DestroyEntities();
        /** Packet ID */
        public Play_Client_DestroyEntities_Builder packetId(int packetId) {
            object.packetId = packetId;
            return this;
        }
        /** Number of elements in the following array */
        public Play_Client_DestroyEntities_Builder count(int count) {
            object.count = count;
            return this;
        }
        /** The list of entities of destroy */
        public Play_Client_DestroyEntities_Builder entityIds(int[] entityIds) {
            object.entityIds = entityIds;
            return this;
        }
        public Play_Client_DestroyEntities build() {
             return object;
        }

    }
    public static Play_Client_DestroyEntities_Builder builder() {
        return new Play_Client_DestroyEntities_Builder();
    }
}