package pub.qiuf.litemc.protocol.play.client;

import pub.qiuf.litemc.common.bean.datatype.Packet;
import com.google.common.io.ByteArrayDataInput;
import com.google.common.io.ByteStreams;
import pub.qiuf.litemc.common.util.ByteUtils;
import pub.qiuf.litemc.common.annotation.MCType;
import com.google.common.io.ByteArrayDataOutput;
import pub.qiuf.litemc.common.annotation.ServerPacket;
import lombok.Data;
import pub.qiuf.litemc.common.util.StreamUtils;

/**
 * Code is generated by <code>pub.qiuf.litemc.generator.ProtocolGenerator</code>, Please don't modify.<br>
 * See more detail from <a>https://wiki.vg/Protocol</a><br>
 */
@Data
@ServerPacket(0x14)
public class Play_Client_CloseWindow extends Packet {
    /** Packet ID */
    @MCType("VarInt")
    private int packetId = 0x14;
    /** This is the ID of the window that was closed. 0 for inventory. */
    @MCType("UnsignedByte")
    private int windowId;

    @Override
    public byte[] encode() throws Exception {
        ByteArrayDataOutput packet = ByteStreams.newDataOutput();
        // Packet ID
        packet.write(ByteUtils.encodeVarInt(packetId));
        // This is the ID of the window that was closed. 0 for inventory.
        packet.write(ByteUtils.encodeUnsignedByte(windowId));
        return packet.toByteArray();
    }
    @Override
    public void decode(ByteArrayDataInput in) throws Exception {
        // Packet ID
        packetId = StreamUtils.readVarInt(in);
        // This is the ID of the window that was closed. 0 for inventory.
        windowId = StreamUtils.readUnsignedByte(in);
    }
    public static class Play_Client_CloseWindow_Builder {
        private Play_Client_CloseWindow object = new Play_Client_CloseWindow();
        /** Packet ID */
        public Play_Client_CloseWindow_Builder packetId(int packetId) {
            object.packetId = packetId;
            return this;
        }
        /** This is the ID of the window that was closed. 0 for inventory. */
        public Play_Client_CloseWindow_Builder windowId(int windowId) {
            object.windowId = windowId;
            return this;
        }
        public Play_Client_CloseWindow build() {
             return object;
        }

    }
    public static Play_Client_CloseWindow_Builder builder() {
        return new Play_Client_CloseWindow_Builder();
    }
}