package pub.qiuf.litemc.protocol.play.client;

import pub.qiuf.litemc.common.bean.datatype.Packet;
import com.google.common.io.ByteArrayDataInput;
import com.google.common.io.ByteStreams;
import pub.qiuf.litemc.common.util.ByteUtils;
import pub.qiuf.litemc.common.annotation.MCType;
import com.google.common.io.ByteArrayDataOutput;
import pub.qiuf.litemc.common.annotation.ServerPacket;
import lombok.Data;
import pub.qiuf.litemc.common.util.StreamUtils;

/**
 * Code is generated by <code>pub.qiuf.litemc.generator.ProtocolGenerator</code>, Please don't modify.<br>
 * See more detail from <a>https://wiki.vg/Protocol</a><br>
 */
@Data
@ServerPacket(0x49)
public class Play_Client_UpdateHealth extends Packet {
    /** Packet ID */
    @MCType("VarInt")
    private int packetId = 0x49;
    /** 0 or less = dead, 20 = full HP */
    @MCType("Float")
    private float health;
    /** 0–20 */
    @MCType("VarInt")
    private int food;
    /** Seems to vary from 0.0 to 5.0 in integer increments */
    @MCType("Float")
    private float foodSaturation;

    @Override
    public byte[] encode() throws Exception {
        ByteArrayDataOutput packet = ByteStreams.newDataOutput();
        // Packet ID
        packet.write(ByteUtils.encodeVarInt(packetId));
        // 0 or less = dead, 20 = full HP
        packet.write(ByteUtils.encodeFloat(health));
        // 0–20
        packet.write(ByteUtils.encodeVarInt(food));
        // Seems to vary from 0.0 to 5.0 in integer increments
        packet.write(ByteUtils.encodeFloat(foodSaturation));
        return packet.toByteArray();
    }
    @Override
    public void decode(ByteArrayDataInput in) throws Exception {
        // Packet ID
        packetId = StreamUtils.readVarInt(in);
        // 0 or less = dead, 20 = full HP
        health = StreamUtils.readFloat(in);
        // 0–20
        food = StreamUtils.readVarInt(in);
        // Seems to vary from 0.0 to 5.0 in integer increments
        foodSaturation = StreamUtils.readFloat(in);
    }
    public static class Play_Client_UpdateHealth_Builder {
        private Play_Client_UpdateHealth object = new Play_Client_UpdateHealth();
        /** Packet ID */
        public Play_Client_UpdateHealth_Builder packetId(int packetId) {
            object.packetId = packetId;
            return this;
        }
        /** 0 or less = dead, 20 = full HP */
        public Play_Client_UpdateHealth_Builder health(float health) {
            object.health = health;
            return this;
        }
        /** 0–20 */
        public Play_Client_UpdateHealth_Builder food(int food) {
            object.food = food;
            return this;
        }
        /** Seems to vary from 0.0 to 5.0 in integer increments */
        public Play_Client_UpdateHealth_Builder foodSaturation(float foodSaturation) {
            object.foodSaturation = foodSaturation;
            return this;
        }
        public Play_Client_UpdateHealth build() {
             return object;
        }

    }
    public static Play_Client_UpdateHealth_Builder builder() {
        return new Play_Client_UpdateHealth_Builder();
    }
}