package pub.qiuf.litemc.protocol.play.client;

import pub.qiuf.litemc.common.bean.datatype.Packet;
import com.google.common.io.ByteArrayDataInput;
import com.google.common.io.ByteStreams;
import pub.qiuf.litemc.common.util.ByteUtils;
import pub.qiuf.litemc.common.annotation.MCType;
import com.google.common.io.ByteArrayDataOutput;
import pub.qiuf.litemc.common.annotation.ServerPacket;
import lombok.Data;
import pub.qiuf.litemc.common.util.StreamUtils;

/**
 * Code is generated by <code>pub.qiuf.litemc.generator.ProtocolGenerator</code>, Please don't modify.<br>
 * See more detail from <a>https://wiki.vg/Protocol</a><br>
 */
@Data
@ServerPacket(0x00)
public class Play_Client_SpawnEntity extends Packet {
    /** Packet ID */
    @MCType("VarInt")
    private int packetId = 0x00;
    /** EID of the entity */
    @MCType("VarInt")
    private int entityId;
    @MCType("UUID")
    private long[] objectUuid = new long[2];
    /** The type of entity (same as in Spawn Living Entity) */
    @MCType("VarInt")
    private int type;
    @MCType("Double")
    private double x;
    @MCType("Double")
    private double y;
    @MCType("Double")
    private double z;
    @MCType("Angle")
    private byte pitch;
    @MCType("Angle")
    private byte yaw;
    /** Meaning dependent on the value of the Type field, see Object Data for details. */
    @MCType("Int")
    private int data;
    /** Same units as Entity Velocity. Always sent, but only used when Data is greater than 0 (except for some entities which always ignore it; see Object Data for details). */
    @MCType("Short")
    private short velocityX;
    @MCType("Short")
    private short velocityY;
    @MCType("Short")
    private short velocityZ;

    @Override
    public byte[] encode() throws Exception {
        ByteArrayDataOutput packet = ByteStreams.newDataOutput();
        // Packet ID
        packet.write(ByteUtils.encodeVarInt(packetId));
        // EID of the entity
        packet.write(ByteUtils.encodeVarInt(entityId));
        for (long temp : objectUuid) {
            packet.write(ByteUtils.encodeLong(temp));
        }
        // The type of entity (same as in Spawn Living Entity)
        packet.write(ByteUtils.encodeVarInt(type));
        packet.write(ByteUtils.encodeDouble(x));
        packet.write(ByteUtils.encodeDouble(y));
        packet.write(ByteUtils.encodeDouble(z));
        packet.write(ByteUtils.encodeAngle(pitch));
        packet.write(ByteUtils.encodeAngle(yaw));
        // Meaning dependent on the value of the Type field, see Object Data for details.
        packet.write(ByteUtils.encodeInt(data));
        // Same units as Entity Velocity. Always sent, but only used when Data is greater than 0 (except for some entities which always ignore it; see Object Data for details).
        packet.write(ByteUtils.encodeShort(velocityX));
        packet.write(ByteUtils.encodeShort(velocityY));
        packet.write(ByteUtils.encodeShort(velocityZ));
        return packet.toByteArray();
    }
    @Override
    public void decode(ByteArrayDataInput in) throws Exception {
        // Packet ID
        packetId = StreamUtils.readVarInt(in);
        // EID of the entity
        entityId = StreamUtils.readVarInt(in);
        // TODO decode objectUuid
        // The type of entity (same as in Spawn Living Entity)
        type = StreamUtils.readVarInt(in);
        x = StreamUtils.readDouble(in);
        y = StreamUtils.readDouble(in);
        z = StreamUtils.readDouble(in);
        pitch = StreamUtils.readAngle(in);
        yaw = StreamUtils.readAngle(in);
        // Meaning dependent on the value of the Type field, see Object Data for details.
        data = StreamUtils.readInt(in);
        // Same units as Entity Velocity. Always sent, but only used when Data is greater than 0 (except for some entities which always ignore it; see Object Data for details).
        velocityX = StreamUtils.readShort(in);
        velocityY = StreamUtils.readShort(in);
        velocityZ = StreamUtils.readShort(in);
    }
    public static class Play_Client_SpawnEntity_Builder {
        private Play_Client_SpawnEntity object = new Play_Client_SpawnEntity();
        /** Packet ID */
        public Play_Client_SpawnEntity_Builder packetId(int packetId) {
            object.packetId = packetId;
            return this;
        }
        /** EID of the entity */
        public Play_Client_SpawnEntity_Builder entityId(int entityId) {
            object.entityId = entityId;
            return this;
        }
        public Play_Client_SpawnEntity_Builder objectUuid(long[] objectUuid) {
            object.objectUuid = objectUuid;
            return this;
        }
        /** The type of entity (same as in Spawn Living Entity) */
        public Play_Client_SpawnEntity_Builder type(int type) {
            object.type = type;
            return this;
        }
        public Play_Client_SpawnEntity_Builder x(double x) {
            object.x = x;
            return this;
        }
        public Play_Client_SpawnEntity_Builder y(double y) {
            object.y = y;
            return this;
        }
        public Play_Client_SpawnEntity_Builder z(double z) {
            object.z = z;
            return this;
        }
        public Play_Client_SpawnEntity_Builder pitch(byte pitch) {
            object.pitch = pitch;
            return this;
        }
        public Play_Client_SpawnEntity_Builder yaw(byte yaw) {
            object.yaw = yaw;
            return this;
        }
        /** Meaning dependent on the value of the Type field, see Object Data for details. */
        public Play_Client_SpawnEntity_Builder data(int data) {
            object.data = data;
            return this;
        }
        /** Same units as Entity Velocity. Always sent, but only used when Data is greater than 0 (except for some entities which always ignore it; see Object Data for details). */
        public Play_Client_SpawnEntity_Builder velocityX(short velocityX) {
            object.velocityX = velocityX;
            return this;
        }
        public Play_Client_SpawnEntity_Builder velocityY(short velocityY) {
            object.velocityY = velocityY;
            return this;
        }
        public Play_Client_SpawnEntity_Builder velocityZ(short velocityZ) {
            object.velocityZ = velocityZ;
            return this;
        }
        public Play_Client_SpawnEntity build() {
             return object;
        }

    }
    public static Play_Client_SpawnEntity_Builder builder() {
        return new Play_Client_SpawnEntity_Builder();
    }
}