package pub.qiuf.litemc.protocol.play.client;

import pub.qiuf.litemc.common.bean.datatype.Packet;
import com.google.common.io.ByteArrayDataInput;
import com.google.common.io.ByteStreams;
import pub.qiuf.litemc.common.util.ByteUtils;
import pub.qiuf.litemc.common.annotation.MCType;
import com.google.common.io.ByteArrayDataOutput;
import pub.qiuf.litemc.common.annotation.ServerPacket;
import lombok.Data;
import pub.qiuf.litemc.common.util.StreamUtils;

/**
 * Code is generated by <code>pub.qiuf.litemc.generator.ProtocolGenerator</code>, Please don't modify.<br>
 * See more detail from <a>https://wiki.vg/Protocol</a><br>
 */
@Data
@ServerPacket(0x48)
public class Play_Client_SetExperience extends Packet {
    /** Packet ID */
    @MCType("VarInt")
    private int packetId = 0x48;
    /** Between 0 and 1 */
    @MCType("Float")
    private float experienceBar;
    @MCType("VarInt")
    private int level;
    /** See Experience#Leveling up on the Minecraft Wiki for Total Experience to Level conversion */
    @MCType("VarInt")
    private int totalExperience;

    @Override
    public byte[] encode() throws Exception {
        ByteArrayDataOutput packet = ByteStreams.newDataOutput();
        // Packet ID
        packet.write(ByteUtils.encodeVarInt(packetId));
        // Between 0 and 1
        packet.write(ByteUtils.encodeFloat(experienceBar));
        packet.write(ByteUtils.encodeVarInt(level));
        // See Experience#Leveling up on the Minecraft Wiki for Total Experience to Level conversion
        packet.write(ByteUtils.encodeVarInt(totalExperience));
        return packet.toByteArray();
    }
    @Override
    public void decode(ByteArrayDataInput in) throws Exception {
        // Packet ID
        packetId = StreamUtils.readVarInt(in);
        // Between 0 and 1
        experienceBar = StreamUtils.readFloat(in);
        level = StreamUtils.readVarInt(in);
        // See Experience#Leveling up on the Minecraft Wiki for Total Experience to Level conversion
        totalExperience = StreamUtils.readVarInt(in);
    }
    public static class Play_Client_SetExperience_Builder {
        private Play_Client_SetExperience object = new Play_Client_SetExperience();
        /** Packet ID */
        public Play_Client_SetExperience_Builder packetId(int packetId) {
            object.packetId = packetId;
            return this;
        }
        /** Between 0 and 1 */
        public Play_Client_SetExperience_Builder experienceBar(float experienceBar) {
            object.experienceBar = experienceBar;
            return this;
        }
        public Play_Client_SetExperience_Builder level(int level) {
            object.level = level;
            return this;
        }
        /** See Experience#Leveling up on the Minecraft Wiki for Total Experience to Level conversion */
        public Play_Client_SetExperience_Builder totalExperience(int totalExperience) {
            object.totalExperience = totalExperience;
            return this;
        }
        public Play_Client_SetExperience build() {
             return object;
        }

    }
    public static Play_Client_SetExperience_Builder builder() {
        return new Play_Client_SetExperience_Builder();
    }
}